"""Etapa 06 — Erguendo os Escudos de Defesa."""

def topico_login_etapa_6():
    while True:
        print()
        print("=" * 60)
        print('🔐 TÓPICO 1: LOGIN')
        print("=" * 60)
        print('Um sistema sério precisa saber quem está tentando entrar.')
        print()
        print('Login é o momento em que a pessoa se apresenta ao sistema.')
        print()
        print('Débora aparece na tela e olha diretamente para você.')
        print()
        print('"Pensa na entrada de um prédio."')
        print('"Antes de liberar a catraca, alguém precisa saber quem você é."')
        print()
        print('Ideia de sobrevivência:')
        print('login é o começo da identificação do usuário.')
        print()
        print("PERGUNTA:")
        print('Quando uma pessoa abre um app e informa quem ela é para tentar entrar,')
        print('qual ideia está começando ali?')
        print()
        print('1 - Autorização, porque o sistema já decidiu tudo que ela pode fazer.')
        print('2 - Login, porque a pessoa está se apresentando ao sistema.')
        print('3 - Banco de dados, porque a tela está criando uma tabela nova.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Débora confirma.')
            print('"Isso. Login é o momento em que a pessoa se apresenta ao sistema."')
            print('"É o começo da portaria digital."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Débora reancora com calma.')
            print('"Quase. Autorização vem depois, quando o sistema decide o que a pessoa pode acessar."')
            print('"Antes disso, a pessoa precisa começar se apresentando."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Débora aponta para a entrada.')
            print('"Boa tentativa. Banco de dados guarda informações, mas login não é criar tabela."')
            print('"Login é o começo da entrada da pessoa no sistema."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_autenticacao_etapa_6():
    while True:
        print()
        print("=" * 60)
        print('🪪 TÓPICO 2: AUTENTICAÇÃO')
        print("=" * 60)
        print('Não basta dizer quem você é.')
        print('O sistema precisa conferir se aquilo é verdade.')
        print()
        print('Autenticação é essa conferência.')
        print()
        print('Pode acontecer com senha, digital, código no celular ou outro tipo de prova.')
        print()
        print('Débora aponta para uma lista de entrada.')
        print()
        print('"Dizer o nome é uma coisa."')
        print('"Provar que é você é outra."')
        print()
        print('Ideia de sobrevivência:')
        print('autenticação responde: quem é você?')
        print()
        print("PERGUNTA:")
        print('Depois que a pessoa informa quem diz ser, o que a autenticação faz?')
        print()
        print('1 - Escolhe as cores da tela de login.')
        print('2 - Decide se a pessoa pode acessar todas as áreas internas.')
        print('3 - Confere se a prova apresentada combina com a identidade da pessoa.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '3':
            print()
            print('Débora confirma.')
            print('"Isso. Autenticação é a conferência da identidade."')
            print('"Ela responde: quem é você?"')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Débora reancora com calma.')
            print('"Quase. Cores e aparência pertencem à interface visual."')
            print('"Autenticação não cuida da aparência; ela confere identidade."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '2':
            print()
            print('Débora separa as perguntas da portaria.')
            print('"Boa tentativa. Decidir o que a pessoa pode acessar é autorização."')
            print('"Autenticação responde primeiro: essa pessoa é quem diz ser?"')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_autorizacao_etapa_6():
    while True:
        print()
        print("=" * 60)
        print('🚪 TÓPICO 3: AUTORIZAÇÃO')
        print("=" * 60)
        print('Entrar no sistema não significa poder mexer em tudo.')
        print()
        print('Autorização define o que a pessoa pode acessar ou fazer.')
        print()
        print('Um cliente pode ver o próprio pedido.')
        print('Um funcionário pode ver ferramentas internas.')
        print('Um administrador pode ter mais permissões.')
        print()
        print('Débora aponta para portas diferentes dentro da CampOne.')
        print()
        print('"Depois de saber quem você é, o sistema pergunta: o que você pode?"')
        print()
        print('Ideia de sobrevivência:')
        print('autorização responde: o que você pode fazer?')
        print()
        print("PERGUNTA:")
        print('Uma pessoa conseguiu entrar no sistema, mas não pode abrir a área financeira.')
        print('Qual peça explica melhor isso?')
        print()
        print('1 - Autorização, porque ela define o que a pessoa pode acessar ou fazer.')
        print('2 - Login, porque entrar sempre libera todas as áreas.')
        print('3 - CSS, porque área financeira bloqueada é problema de aparência.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            print()
            print('Débora confirma.')
            print('"Isso. Autorização define o que a pessoa pode fazer depois que entra."')
            print('"Passar pela porta não significa abrir todas as salas."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '2':
            print()
            print('Débora reancora com calma.')
            print('"Quase. Entrar no sistema não significa poder mexer em tudo."')
            print('"Depois da entrada, o sistema ainda verifica permissões."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Débora aponta para outra área.')
            print('"Boa tentativa, mas CSS cuida da aparência visual."')
            print('"Área restrita é assunto de permissão, não de cor ou layout."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_cookies_etapa_6():
    while True:
        print()
        print("=" * 60)
        print('🍪 TÓPICO 4: COOKIES')
        print("=" * 60)
        print('A web tem um problema:')
        print('cada pedido pode chegar como se fosse a primeira visita.')
        print()
        print('Cookies ajudam o navegador a guardar pequenas informações.')
        print()
        print('No contexto de login, eles podem ajudar o sistema a lembrar')
        print('que aquela pessoa já passou por uma identificação.')
        print()
        print('Débora mostra uma pulseira de entrada.')
        print()
        print('"Depois que você entra, não precisa mostrar documento a cada porta."')
        print('"Mas existe um lembrete acompanhando você."')
        print()
        print('Ideia de sobrevivência:')
        print('cookie é um pequeno lembrete guardado pelo navegador.')
        print()
        print("PERGUNTA:")
        print('Por que cookies podem ajudar depois que a pessoa entra em um sistema?')
        print()
        print('1 - Porque cookies substituem toda segurança e deixam qualquer pessoa entrar.')
        print('2 - Porque podem guardar pequenos lembretes no navegador, ajudando o sistema a reconhecer uma visita.')
        print('3 - Porque cookies apagam automaticamente todas as senhas do usuário.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Débora confirma.')
            print('"Isso. Cookie pode funcionar como um lembrete guardado pelo navegador."')
            print('"Ele ajuda o sistema a reconhecer algumas informações entre pedidos."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Débora reancora com calma.')
            print('"Quase. Cookie não substitui toda a segurança."')
            print('"Ele pode ajudar como lembrete, mas o sistema ainda precisa de regras de proteção."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Débora aponta para a função do lembrete.')
            print('"Boa tentativa, mas cookie não é uma borracha de senha."')
            print('"Aqui a ideia é guardar um pequeno lembrete no navegador."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_sessao_etapa_6():
    while True:
        print()
        print("=" * 60)
        print('⏳ TÓPICO 5: SESSÃO')
        print("=" * 60)
        print('Depois que a pessoa entra, o sistema mantém esse acesso por um tempo.')
        print()
        print('Esse período é a sessão.')
        print()
        print('Sessão não deve durar para sempre.')
        print('Ela pode expirar por segurança, principalmente em sistemas sensíveis.')
        print()
        print('Débora olha diretamente para você.')
        print()
        print('"Se alguém pega seu celular desbloqueado, uma sessão eterna vira perigo."')
        print()
        print('Ideia de sobrevivência:')
        print('sessão é o tempo em que o sistema continua reconhecendo você.')
        print()
        print("PERGUNTA:")
        print('Por que uma sessão não deve durar para sempre?')
        print()
        print('1 - Porque toda sessão serve para mudar a cor da tela.')
        print('2 - Porque sessão eterna deixa o banco de dados sem tabelas.')
        print('3 - Porque manter acesso aberto para sempre pode colocar a conta em risco.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '3':
            print()
            print('Débora confirma.')
            print('"Isso. Sessão precisa ter limite."')
            print('"Se o acesso ficasse aberto para sempre, outra pessoa poderia aproveitar isso."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Débora reancora com calma.')
            print('"Quase. Cor da tela é assunto de interface."')
            print('"Sessão fala sobre o tempo em que o sistema continua reconhecendo a pessoa."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '2':
            print()
            print('Débora aponta para o risco real.')
            print('"Boa tentativa, mas sessão não apaga tabelas do banco."')
            print('"O ponto aqui é segurança do acesso."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_token_etapa_6():
    while True:
        print()
        print("=" * 60)
        print('🎟️ TÓPICO 6: TOKEN')
        print("=" * 60)
        print('Depois de entrar, o sistema pode entregar uma prova temporária.')
        print()
        print('Essa prova acompanha os próximos pedidos.')
        print()
        print('Token é como um crachá digital temporário.')
        print('Ele ajuda o sistema a reconhecer que aquele pedido vem de alguém já conferido.')
        print()
        print('Débora mostra um crachá com validade.')
        print()
        print('"O crachá ajuda na passagem, mas não deve valer para sempre."')
        print()
        print('Ideia de sobrevivência:')
        print('token é uma prova temporária usada para reconhecer pedidos.')
        print()
        print("PERGUNTA:")
        print('Depois que a pessoa já foi conferida,')
        print('por que um token pode acompanhar os próximos pedidos?')
        print()
        print('1 - Porque funciona como uma prova temporária de que aquele pedido vem de alguém já reconhecido.')
        print('2 - Porque token é uma imagem decorativa que aparece no botão de login.')
        print('3 - Porque token substitui todas as permissões e libera tudo para qualquer pessoa.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            print()
            print('Débora confirma.')
            print('"Isso. Token funciona como um crachá digital temporário."')
            print('"Ele ajuda o sistema a reconhecer pedidos depois do login."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '2':
            print()
            print('Débora reancora com calma.')
            print('"Quase. Imagem decorativa é assunto de interface visual."')
            print('"Token não é decoração; é uma prova temporária usada nos pedidos."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Débora aponta para os limites da portaria.')
            print('"Boa tentativa, mas token não deve liberar tudo para qualquer pessoa."')
            print('"Ele ajuda a reconhecer pedidos, mas o sistema ainda precisa respeitar permissões."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_seguranca_completa_etapa_6():
    while True:
        print()
        print("=" * 60)
        print('🛡️ TÓPICO 7: SEGURANÇA COMPLETA')
        print("=" * 60)
        print('Agora juntamos as peças da portaria digital.')
        print()
        print('Login inicia a entrada.')
        print('Autenticação confere quem é a pessoa.')
        print('Autorização define o que ela pode fazer.')
        print('Cookies podem guardar pequenos lembretes no navegador.')
        print('Sessão mantém o reconhecimento por um tempo.')
        print('Token pode funcionar como uma prova temporária nos pedidos.')
        print()
        print('Débora cruza os braços com calma.')
        print()
        print('"Segurança não é impedir tudo."')
        print('"É deixar a pessoa certa entrar, pelo tempo certo, no lugar certo."')
        print()
        print('Ideia de sobrevivência:')
        print('segurança organiza identidade, permissão e tempo de acesso.')
        print()
        print("PERGUNTA:")
        print('Qual frase resume melhor a portaria digital de um sistema?')
        print()
        print('1 - Segurança é impedir todo mundo de entrar, mesmo quem tem permissão.')
        print('2 - Segurança é deixar a pessoa certa entrar, pelo tempo certo, no lugar certo.')
        print('3 - Segurança é trocar cores da tela e aumentar o tamanho dos botões.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Débora confirma.')
            print('"Isso. Segurança é equilíbrio."')
            print('"A pessoa certa, no lugar certo, pelo tempo certo."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Débora reancora com calma.')
            print('"Quase. Segurança não é travar tudo."')
            print('"Ela precisa proteger sem impedir a pessoa certa de usar o sistema."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Débora aponta para outro território.')
            print('"Boa tentativa, mas cores e botões pertencem à interface visual."')
            print('"Segurança organiza identidade, permissão e tempo de acesso."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def cena_abertura_etapa_6():
    print()
    print("=" * 60)
    print("🎬 INICIAR MISSÃO: A PORTARIA DIGITAL")
    print("=" * 60)
    print("Você chega à entrada da CampOne.")
    print()
    print("Depois de atravessar a Grande Rede,")
    print("entender o Motor Oculto,")
    print("organizar a memória do sistema,")
    print("cruzar a ponte entre tela e backend")
    print("e enxergar a interface visual,")
    print("uma nova pergunta aparece:")
    print()
    print("quem pode entrar no sistema?")
    print("e o que essa pessoa pode fazer depois que entra?")
    print()
    print("Débora aparece na tela e olha diretamente para você.")
    print()
    print('"Olá. Eu sou Débora."')
    print()
    print('"Minha área é Login e Segurança."')
    print('"Eu cuido da portaria digital da CampOne."')
    print()
    print('"Todo sistema sério precisa fazer duas perguntas:"')
    print()
    print('"Quem é você?"')
    print('"E o que você pode acessar?"')
    print()
    print("Débora aponta para uma catraca digital.")
    print()
    print('"Login, autenticação, autorização, sessão, cookies e tokens"')
    print('"não são palavras para decorar."')
    print()
    print('"São partes de uma mesma ideia:"')
    print('"deixar a pessoa certa entrar, pelo tempo certo, no lugar certo."')
    print()
    print("Nesta etapa, você vai entender:")
    print()
    print("- por que sistemas pedem login;")
    print("- como o sistema confirma quem é a pessoa;")
    print("- por que entrar não significa poder fazer tudo;")
    print("- como o navegador pode guardar pequenos lembretes;")
    print("- por que uma sessão não deve durar para sempre;")
    print("- como uma prova temporária pode acompanhar os pedidos;")
    print("- e por que segurança também é cuidado com o usuário.")
    print()
    print("Débora conclui:")
    print()
    print('"Segurança não é travar tudo."')
    print('"É proteger o caminho sem impedir a pessoa certa de trabalhar."')
    print()
    print('"Sem sintaxe disfarçada."')
    print('"Primeiro você entende a portaria."')
    print('"Depois, no mundo prático, aprende a operar as ferramentas."')
    print("=" * 60)

    input("Pressione Enter para voltar...")


def reconhecimento_etapa_6():
    while True:
        print()
        print("=" * 60)
        print("💡 RECONHECIMENTO: A PORTARIA DIGITAL")
        print("=" * 60)
        print("Débora organiza os primeiros conceitos de Login e Segurança.")
        print()
        print("1 - Login")
        print("2 - Autenticação")
        print("3 - Autorização")
        print("4 - Cookies")
        print("5 - Sessão")
        print("6 - Token")
        print("7 - Segurança completa")
        print("0 - Voltar à etapa 06")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            topico_login_etapa_6()
        elif escolha == "2":
            topico_autenticacao_etapa_6()
        elif escolha == "3":
            topico_autorizacao_etapa_6()
        elif escolha == "4":
            topico_cookies_etapa_6()
        elif escolha == "5":
            topico_sessao_etapa_6()
        elif escolha == "6":
            topico_token_etapa_6()
        elif escolha == "7":
            topico_seguranca_completa_etapa_6()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")


def campo_treinamento_etapa_6():
    print()
    print("=" * 60)
    print("🛠️ CAMPO DE TREINAMENTO: O CAMINHO DO LOGIN")
    print("=" * 60)
    print("Débora aparece na tela e olha diretamente para você.")
    print()
    print("Agora vamos acompanhar uma entrada segura por dentro do sistema.")
    print()
    print("Cena:")
    print("Uma pessoa abre o app da CampOne e tenta entrar na própria conta.")
    print()
    print("-" * 60)
    print("1. A PESSOA SE APRESENTA")
    print("-" * 60)
    print("A pessoa informa quem ela diz ser.")
    print()
    print("No mundo real, isso pode ser e-mail, senha, digital, código no celular")
    print("ou outra forma de identificação.")
    print()
    print("Ideia:")
    print("o sistema precisa saber quem está tentando entrar.")
    print()
    print("-" * 60)
    print("2. O SISTEMA CONFERE")
    print("-" * 60)
    print("Não basta a pessoa dizer quem é.")
    print("O sistema precisa conferir se a prova combina.")
    print()
    print("Essa conferência é a autenticação.")
    print()
    print("Ideia:")
    print("autenticação responde: quem é você?")
    print()
    print("-" * 60)
    print("3. O SISTEMA LIBERA OU RECUSA")
    print("-" * 60)
    print("Se a prova não confere, a entrada é recusada.")
    print()
    print("Se confere, a pessoa entra.")
    print()
    print("Mas entrar não significa poder mexer em tudo.")
    print()
    print("-" * 60)
    print("4. O SISTEMA VERIFICA PERMISSÕES")
    print("-" * 60)
    print("Depois de reconhecer a pessoa, o sistema olha o que ela pode fazer.")
    print()
    print("Um cliente pode ver a própria conta.")
    print("Um funcionário pode ver ferramentas internas.")
    print("Um administrador pode ter mais acesso.")
    print()
    print("Essa parte é a autorização.")
    print()
    print("Ideia:")
    print("autorização responde: o que você pode fazer?")
    print()
    print("-" * 60)
    print("5. O SISTEMA LEMBRA POR UM TEMPO")
    print("-" * 60)
    print("Depois da entrada, o sistema pode manter a pessoa reconhecida por um período.")
    print()
    print("Esse período é a sessão.")
    print()
    print("Ela existe para a pessoa não precisar provar quem é a cada clique.")
    print("Mas ela não deve durar para sempre.")
    print()
    print("-" * 60)
    print("6. OS PRÓXIMOS PEDIDOS LEVAM UMA PROVA")
    print("-" * 60)
    print("Enquanto a sessão está válida, os próximos pedidos podem levar uma prova temporária.")
    print()
    print("Essa prova ajuda o sistema a reconhecer que o pedido vem de alguém já conferido.")
    print()
    print("Essa ideia aparece no token.")
    print()
    print("-" * 60)
    print("RESUMO DO CAMINHO")
    print("-" * 60)
    print("A pessoa tenta entrar.")
    print("O sistema confere quem ela é.")
    print("O sistema verifica o que ela pode fazer.")
    print("O acesso vale por um tempo.")
    print("Os pedidos seguintes carregam uma prova temporária.")
    print()
    print("Ideia de sobrevivência:")
    print("segurança é deixar a pessoa certa entrar, pelo tempo certo, no lugar certo.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def laboratorio_falhas_etapa_6():
    print()
    print("=" * 60)
    print("🧪 LABORATÓRIO DE FALHAS: OCORRÊNCIAS DA PORTARIA")
    print("=" * 60)
    print("Débora aparece na tela e olha diretamente para você.")
    print()
    print("Agora vamos olhar ocorrências comuns de segurança.")
    print()
    print("A ideia não é chamar tudo de erro.")
    print("Às vezes, a portaria está apenas fazendo o trabalho dela.")
    print()
    print("-" * 60)
    print("OCORRÊNCIA 1 — SENHA ERRADA")
    print("-" * 60)
    print("Uma pessoa tenta entrar no app e digita a senha errada.")
    print()
    print("O sistema recusa a entrada.")
    print()
    print("Peça em jogo:")
    print("autenticação.")
    print()
    print("Por quê?")
    print("O sistema está conferindo se a pessoa é mesmo quem diz ser.")
    print("Se a prova não confere, a entrada não deve ser liberada.")
    print()
    print("Diagnóstico:")
    print("não é bug por padrão; é a portaria funcionando.")
    print()
    print("-" * 60)
    print("OCORRÊNCIA 2 — SESSÃO EXPIRADA")
    print("-" * 60)
    print("A pessoa entrou de manhã, usou o app e voltou horas depois.")
    print("O app pediu login novamente.")
    print()
    print("Peça em jogo:")
    print("sessão.")
    print()
    print("Por quê?")
    print("O reconhecimento da pessoa não deve durar para sempre.")
    print("Em sistemas sensíveis, expirar a sessão protege o usuário.")
    print()
    print("Diagnóstico:")
    print("não é bug por padrão; é uma regra de segurança.")
    print()
    print("-" * 60)
    print("OCORRÊNCIA 3 — ÁREA RESTRITA")
    print("-" * 60)
    print("Um funcionário consegue entrar no sistema,")
    print("mas não consegue acessar o módulo financeiro.")
    print()
    print("Peça em jogo:")
    print("autorização.")
    print()
    print("Por quê?")
    print("Ele provou quem é, mas talvez não tenha permissão para aquela área.")
    print()
    print("Diagnóstico:")
    print("não é bug por padrão; pode ser a permissão funcionando corretamente.")
    print()
    print("-" * 60)
    print("OCORRÊNCIA 4 — PEDIDO SEM CRACHÁ")
    print("-" * 60)
    print("Um pedido chega ao backend pedindo dados protegidos,")
    print("mas não traz nenhuma prova temporária de quem está pedindo.")
    print()
    print("Peça em jogo:")
    print("token ou sessão ausente.")
    print()
    print("Por quê?")
    print("O sistema não deve entregar dados protegidos sem reconhecer a pessoa.")
    print()
    print("Diagnóstico:")
    print("a resposta pode ser uma recusa de segurança, como falta de identificação.")
    print()
    print("-" * 60)
    print("IDEIA DE SOBREVIVÊNCIA")
    print("-" * 60)
    print("Nem toda recusa é defeito.")
    print()
    print("Às vezes, segurança é justamente dizer:")
    print("não posso liberar isso sem saber quem você é,")
    print("sem saber o que você pode fazer,")
    print("ou depois que seu acesso expirou.")
    print()
    print("Uma boa portaria protege sem virar bagunça.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def missao_producao_etapa_6():
    print()
    print("=" * 60)
    print("🏢 MISSÃO EM PRODUÇÃO: SEGURANÇA NO APP REAL")
    print("=" * 60)
    print("Débora aparece na tela e olha diretamente para você.")
    print()
    print("Agora a portaria digital sai do treinamento e entra em produção.")
    print()
    print("Imagine o app da CampOne sendo usado por três pessoas:")
    print()
    print("- um cliente;")
    print("- um funcionário;")
    print("- uma pessoa administradora.")
    print()
    print("Todas podem entrar no sistema,")
    print("mas cada uma deve enxergar e fazer coisas diferentes.")
    print()
    print("-" * 60)
    print("CENA 1 — CLIENTE ENTRANDO")
    print("-" * 60)
    print("O cliente abre o app e informa suas credenciais.")
    print()
    print("O sistema confere quem ele é.")
    print()
    print("Se a prova estiver correta, o cliente entra.")
    print()
    print("Depois disso, ele pode ver a própria conta,")
    print("os próprios pedidos")
    print("e informações liberadas para ele.")
    print()
    print("Ideia:")
    print("autenticação confirma quem é a pessoa.")
    print()
    print("-" * 60)
    print("CENA 2 — FUNCIONÁRIO COM ACESSO LIMITADO")
    print("-" * 60)
    print("Um funcionário entra no sistema.")
    print()
    print("Ele consegue abrir o painel de atendimento,")
    print("mas não consegue abrir uma área financeira restrita.")
    print()
    print("Isso não precisa ser bug.")
    print()
    print("Pode ser autorização funcionando.")
    print()
    print("Ideia:")
    print("entrar no sistema não significa poder mexer em tudo.")
    print()
    print("-" * 60)
    print("CENA 3 — SESSÃO EXPIRADA")
    print("-" * 60)
    print("Uma pessoa fica muito tempo sem usar o app.")
    print()
    print("Quando volta, o sistema pede login novamente.")
    print()
    print("Isso pode incomodar,")
    print("mas protege a conta se outra pessoa pegar o dispositivo.")
    print()
    print("Ideia:")
    print("sessão tem prazo por segurança.")
    print()
    print("-" * 60)
    print("CENA 4 — PEDIDO PROTEGIDO")
    print("-" * 60)
    print("A tela tenta pedir dados protegidos ao backend.")
    print()
    print("Esse pedido precisa levar alguma prova de que a pessoa já foi conferida.")
    print()
    print("Se essa prova não aparece,")
    print("o sistema não deve entregar os dados.")
    print()
    print("Ideia:")
    print("token ou sessão ajudam a reconhecer pedidos depois do login.")
    print()
    print("-" * 60)
    print("IDEIA DE SOBREVIVÊNCIA")
    print("-" * 60)
    print("Em produção, segurança não é só uma tela de login.")
    print()
    print("É um conjunto de cuidados:")
    print("confirmar identidade,")
    print("respeitar permissões,")
    print("limitar o tempo de acesso")
    print("e proteger pedidos sensíveis.")
    print()
    print("A portaria digital existe para proteger pessoas, dados e sistemas.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def prova_dominio_etapa_6():
    while True:
        print()
        print("=" * 60)
        print("✅ PROVA DE DOMÍNIO: A PORTARIA DIGITAL")
        print("=" * 60)
        print("Débora aparece na tela e olha diretamente para você.")
        print()
        print('"Agora vamos juntar a portaria inteira em uma cena só."')
        print()
        print("Uma pessoa entra no app,")
        print("prova quem é,")
        print("recebe acesso por um tempo,")
        print("tenta abrir uma área restrita")
        print("e depois faz pedidos protegidos ao backend.")
        print()
        print("PERGUNTA:")
        print("Qual leitura mostra melhor o que está acontecendo?")
        print()
        print("1 - A tela está apenas mudando de cor, então tudo é problema de CSS.")
        print("2 - O banco de dados está aparecendo direto para o usuário e decidindo todos os acessos sozinho.")
        print("3 - O sistema autentica a pessoa, verifica permissões, mantém uma sessão por tempo limitado e usa uma prova temporária nos pedidos protegidos.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "3":
            print()
            print("Débora confirma.")
            print('"Isso. Você juntou a portaria inteira:"')
            print('"identidade, permissão, tempo de acesso e prova temporária nos pedidos."')
            print()
            print("A base teórica de Login e Segurança está dominada.")
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Débora reancora com calma.")
            print('"Quase. Cor e aparência pertencem ao frontend."')
            print('"Aqui estamos falando de entrada, permissão e proteção de pedidos."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "2":
            print()
            print("Débora aponta para a portaria digital.")
            print('"Boa tentativa. O banco guarda dados, mas não deve decidir sozinho o acesso direto do usuário."')
            print('"A portaria digital organiza quem entra, o que pode e por quanto tempo."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def registro_etapa_6():
    print()
    print("=" * 60)
    print("📝 REGISTRAR EXPERIÊNCIA — A PORTARIA DIGITAL")
    print("=" * 60)
    print("Débora aparece na tela e olha diretamente para você.")
    print()
    print("Vamos registrar o que você entendeu sobre os escudos de defesa.")
    print()
    print("Você reconheceu que:")
    print()
    print("- login é o começo da entrada no sistema;")
    print("- autenticação confirma quem a pessoa é;")
    print("- autorização define o que a pessoa pode fazer;")
    print("- cookies podem guardar pequenos lembretes no navegador;")
    print("- sessão mantém o reconhecimento por um tempo limitado;")
    print("- token pode funcionar como uma prova temporária nos pedidos;")
    print("- nem toda recusa é defeito;")
    print("- segurança protege pessoas, dados e sistemas.")
    print()
    print("Débora confirma:")
    print("Isso ainda não é programação prática.")
    print("É visão de segurança.")
    print()
    print("Experiência registrada apenas na narrativa.")
    print("Salvamento real será criado em uma fase futura.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def relatorio_final_etapa_6():
    print()
    print("=" * 60)
    print("📋 RELATÓRIO FINAL — A PORTARIA DIGITAL")
    print("=" * 60)
    print("Débora aparece na tela e olha diretamente para você.")
    print()
    print("Relatório da missão: Erguendo os Escudos de Defesa")
    print()
    print("Você agora sabe que:")
    print()
    print("- todo sistema sério precisa saber quem está tentando entrar;")
    print("- login inicia a entrada;")
    print("- autenticação confere identidade;")
    print("- autorização controla permissões;")
    print("- cookies podem guardar pequenos lembretes no navegador;")
    print("- sessão limita o tempo de reconhecimento;")
    print("- token pode acompanhar pedidos protegidos;")
    print("- segurança não é travar tudo;")
    print("- segurança é permitir a pessoa certa, no lugar certo, pelo tempo certo.")
    print()
    print("Conclusão:")
    print()
    print("Login não é só uma tela com senha.")
    print("É uma portaria digital.")
    print("Ela protege o caminho entre pessoa, sistema, dados e permissões.")
    print()
    print("A etapa ainda não marca conclusão permanente nesta versão.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def entrar_etapa_6():
    while True:
        print()
        print("=" * 60)
        print("06. ERGUENDO OS ESCUDOS DE DEFESA")
        print("=" * 60)
        print("Tema real: Login e Segurança")
        print("Tipo: Treinamento de Sobrevivência")
        print("Status: Estrutura inicial")
        print("Mentora prevista: Débora")
        print()
        print("CENTRO DE OPERAÇÕES")
        print("-" * 60)
        print("1 - Iniciar Missão")
        print("2 - Reconhecimento")
        print("3 - Campo de Treinamento")
        print("4 - Laboratório de Falhas")
        print("5 - Missão em Produção")
        print("6 - Prova de Domínio")
        print("7 - Registrar Experiência")
        print("8 - Relatório Final")
        print("0 - Retornar ao Nível 1")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            cena_abertura_etapa_6()
        elif escolha == "2":
            reconhecimento_etapa_6()
        elif escolha == "3":
            campo_treinamento_etapa_6()
        elif escolha == "4":
            laboratorio_falhas_etapa_6()
        elif escolha == "5":
            missao_producao_etapa_6()
        elif escolha == "6":
            prova_dominio_etapa_6()
        elif escolha == "7":
            registro_etapa_6()
        elif escolha == "8":
            relatorio_final_etapa_6()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")
