"""Etapa 08 — O Rito da Grande Implantação."""

def topico_sistema_local_etapa_8():
    while True:
        print()
        print("=" * 60)
        print('🏠 TÓPICO 1: SISTEMA LOCAL')
        print("=" * 60)
        print('Um sistema pode funcionar perfeitamente no computador do desenvolvedor.')
        print()
        print('Mas, se só funciona ali, o cliente ainda não consegue usar.')
        print()
        print('Gabriel aparece na tela e olha diretamente para você.')
        print()
        print('Um sistema preso no computador do dev ainda não virou produto.')
        print()
        print('Ideia de sobrevivência:')
        print('local é o ambiente onde o dev cria e testa antes de publicar.')
        print()
        print("PERGUNTA:")
        print('Por que um sistema funcionando apenas no computador do desenvolvedor')
        print('ainda não é um produto disponível?')
        print()
        print('1 - Porque o computador do dev sempre apaga o banco de dados.')
        print('2 - Porque outras pessoas ainda não conseguem acessar e usar esse sistema.')
        print('3 - Porque sistema local já está automaticamente publicado para clientes.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Gabriel confirma.')
            print('"Isso. Se só funciona no computador do dev, ainda não está disponível para usuários reais."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Gabriel reancora com calma.')
            print('"Quase. O problema não é o banco apagar."')
            print('"O ponto é que o sistema ainda está preso no ambiente do dev."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Gabriel aponta para a diferença entre local e publicado.')
            print('"Boa tentativa, mas local não significa publicado."')
            print('"Local é onde o dev cria e testa."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_deploy_etapa_8():
    while True:
        print()
        print("=" * 60)
        print('🚀 TÓPICO 2: DEPLOY')
        print("=" * 60)
        print('Deploy é o momento em que o sistema sai do ambiente privado')
        print('e vai para um lugar onde outras pessoas conseguem acessar.')
        print()
        print('É como mudar de uma garagem fechada para uma loja com endereço aberto.')
        print()
        print('Gabriel aponta para uma tela de publicação.')
        print()
        print('Deploy não é só apertar um botão.')
        print('É colocar o sistema no ar com cuidado.')
        print()
        print('Ideia de sobrevivência:')
        print('deploy coloca o sistema em funcionamento para usuários reais.')
        print()
        print("PERGUNTA:")
        print('O que melhor descreve o deploy?')
        print()
        print('1 - A mudança que leva o sistema para um ambiente onde usuários conseguem acessar.')
        print('2 - A troca das cores e botões da interface.')
        print('3 - O ato de apagar todo o histórico do Git.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            print()
            print('Gabriel confirma.')
            print('"Isso. Deploy é colocar o sistema em funcionamento para usuários reais."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '2':
            print()
            print('Gabriel reancora com calma.')
            print('"Quase. Cores e botões são assunto de interface."')
            print('"Deploy é sobre disponibilizar o sistema."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Gabriel separa deploy de histórico.')
            print('"Boa tentativa, mas deploy não apaga histórico."')
            print('"Ele leva uma versão para um ambiente acessível."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_servidor_deploy_etapa_8():
    while True:
        print()
        print("=" * 60)
        print('🖥️ TÓPICO 3: SERVIDOR')
        print("=" * 60)
        print('Depois do deploy, o sistema precisa morar em algum lugar.')
        print()
        print('Esse lugar é um servidor.')
        print()
        print('Servidor é a máquina ou ambiente que fica disponível para receber acessos.')
        print()
        print('Gabriel olha diretamente para você.')
        print()
        print('O servidor é a casa onde o sistema fica funcionando fora do computador do dev.')
        print()
        print('Ideia de sobrevivência:')
        print('servidor mantém o sistema disponível para quem precisa usar.')
        print()
        print("PERGUNTA:")
        print('Depois do deploy, por que o sistema precisa de um servidor?')
        print()
        print('1 - Para o usuário escolher a cor do aplicativo.')
        print('2 - Para substituir todos os arquivos do projeto por imagens.')
        print('3 - Para ter um ambiente disponível onde o sistema possa receber acessos.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '3':
            print()
            print('Gabriel confirma.')
            print('"Isso. Servidor é a casa onde o sistema fica disponível fora do computador do dev."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Gabriel reancora com calma.')
            print('"Quase. Cor do aplicativo é assunto de frontend."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '2':
            print()
            print('Gabriel aponta para a função da casa.')
            print('"Boa tentativa, mas servidor não transforma projeto em imagens."')
            print('"Ele hospeda o sistema funcionando."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_dominio_dns_etapa_8():
    while True:
        print()
        print("=" * 60)
        print('🌐 TÓPICO 4: DOMÍNIO E DNS')
        print("=" * 60)
        print('Depois que o sistema tem uma casa, as pessoas precisam encontrar essa casa.')
        print()
        print('Domínio é o nome fácil que a pessoa digita.')
        print('DNS é a agenda que liga esse nome ao endereço real do servidor.')
        print()
        print('Gabriel desenha uma placa de endereço.')
        print()
        print('Sem domínio e DNS configurados, o usuário pode não encontrar o sistema.')
        print()
        print('Ideia de sobrevivência:')
        print('domínio é o nome; DNS aponta esse nome para o servidor certo.')
        print()
        print("PERGUNTA:")
        print('Qual é a relação entre domínio e DNS?')
        print()
        print('1 - Domínio guarda a senha do usuário e DNS desenha a tela.')
        print('2 - Domínio é o nome fácil, e DNS aponta esse nome para o servidor correto.')
        print('3 - Domínio e DNS servem para apagar versões antigas do projeto.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Gabriel confirma.')
            print('"Isso. Domínio é o nome fácil; DNS liga esse nome ao endereço real."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Gabriel reancora com calma.')
            print('"Quase. Senha é segurança; desenho da tela é frontend."')
            print('"Domínio e DNS ajudam a encontrar o sistema."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Gabriel aponta para o endereço.')
            print('"Boa tentativa, mas apagar versões é outro assunto."')
            print('"Aqui falamos de endereço."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_hospedagem_vps_nuvem_etapa_8():
    while True:
        print()
        print("=" * 60)
        print('🏢 TÓPICO 5: HOSPEDAGEM, VPS E NUVEM')
        print("=" * 60)
        print('Existem formas diferentes de dar moradia para um sistema.')
        print()
        print('Hospedagem é a empresa ou serviço que oferece o lugar.')
        print('VPS é como um apartamento separado dentro de uma estrutura maior.')
        print('Nuvem é uma estrutura flexível que pode crescer conforme a necessidade.')
        print()
        print('Gabriel aponta para três tipos de moradia.')
        print()
        print('O melhor caminho depende do tamanho, custo, controle e crescimento do projeto.')
        print()
        print('Ideia de sobrevivência:')
        print('hospedagem é a moradia; VPS e nuvem são modelos possíveis dessa moradia.')
        print()
        print("PERGUNTA:")
        print('O que melhor descreve hospedagem, VPS e nuvem?')
        print()
        print('1 - Formas de dar moradia para o sistema funcionar fora do computador do dev.')
        print('2 - Tipos de botão que aparecem na interface.')
        print('3 - Métodos para criar commits automaticamente.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            print()
            print('Gabriel confirma.')
            print('"Isso. São formas de hospedar o sistema e mantê-lo acessível."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '2':
            print()
            print('Gabriel reancora com calma.')
            print('"Quase. Botões pertencem à interface."')
            print('"Aqui falamos de onde o sistema mora."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Gabriel separa deploy de Git.')
            print('"Boa tentativa. Commits são Git."')
            print('"Hospedagem, VPS e nuvem são moradia e estrutura."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_pipeline_etapa_8():
    while True:
        print()
        print("=" * 60)
        print('🏭 TÓPICO 6: PIPELINE')
        print("=" * 60)
        print('Deploy moderno pode ter uma esteira de segurança.')
        print()
        print('Pipeline é uma sequência organizada que pode conferir, testar e publicar mudanças.')
        print()
        print('Se algo está errado, a esteira pode parar antes de afetar o usuário.')
        print()
        print('Gabriel mostra uma linha de etapas.')
        print()
        print('A pipeline ajuda o time a publicar com mais cuidado e menos improviso.')
        print()
        print('Ideia de sobrevivência:')
        print('pipeline é a esteira que ajuda a levar mudanças para produção com segurança.')
        print()
        print("PERGUNTA:")
        print('Por que uma pipeline ajuda no deploy?')
        print()
        print('1 - Porque ela troca o nome do domínio sozinha todos os dias.')
        print('2 - Porque ela substitui todos os testes por sorte.')
        print('3 - Porque ela organiza etapas para conferir, testar e publicar mudanças com mais segurança.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '3':
            print()
            print('Gabriel confirma.')
            print('"Isso. Pipeline é a esteira que ajuda a publicar com cuidado."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Gabriel reancora com calma.')
            print('"Quase. Domínio é endereço."')
            print('"Pipeline é esteira de publicação."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '2':
            print()
            print('Gabriel aponta para o cuidado.')
            print('"Boa tentativa, mas pipeline não é sorte."')
            print('"Ela existe para reduzir improviso."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_producao_etapa_8():
    while True:
        print()
        print("=" * 60)
        print('🌍 TÓPICO 7: PRODUÇÃO')
        print("=" * 60)
        print('Produção é o ambiente onde usuários reais usam o sistema.')
        print()
        print('Ali, qualquer mudança precisa de cuidado.')
        print()
        print('Uma falha em produção pode afetar clientes, dados e a reputação da empresa.')
        print()
        print('Gabriel fala com seriedade.')
        print()
        print('O melhor deploy é aquele que o usuário nem percebe.')
        print()
        print('Ideia de sobrevivência:')
        print('produção é o mundo real do sistema em funcionamento.')
        print()
        print("PERGUNTA:")
        print('Por que mudanças em produção exigem cuidado?')
        print()
        print('1 - Porque produção é só um desenho sem usuários reais.')
        print('2 - Porque usuários reais podem ser afetados se algo quebrar.')
        print('3 - Porque produção apaga automaticamente todo o código local.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Gabriel confirma.')
            print('"Isso. Produção é o mundo real do sistema, então exige cuidado."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Gabriel reancora com calma.')
            print('"Quase. Produção não é desenho; é o sistema real em uso."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Gabriel aponta para o risco real.')
            print('"Boa tentativa, mas produção não apaga código local."')
            print('"O risco é afetar usuários reais."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def reconhecimento_etapa_8():
    while True:
        print()
        print("=" * 60)
        print("💡 RECONHECIMENTO: O SISTEMA NO AR")
        print("=" * 60)
        print("Gabriel organiza os primeiros conceitos de Deploy.")
        print()
        print("1 - Sistema local")
        print("2 - Deploy")
        print("3 - Servidor")
        print("4 - Domínio e DNS")
        print("5 - Hospedagem, VPS e Nuvem")
        print("6 - Pipeline")
        print("7 - Produção")
        print("0 - Voltar à etapa 08")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            topico_sistema_local_etapa_8()
        elif escolha == "2":
            topico_deploy_etapa_8()
        elif escolha == "3":
            topico_servidor_deploy_etapa_8()
        elif escolha == "4":
            topico_dominio_dns_etapa_8()
        elif escolha == "5":
            topico_hospedagem_vps_nuvem_etapa_8()
        elif escolha == "6":
            topico_pipeline_etapa_8()
        elif escolha == "7":
            topico_producao_etapa_8()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")


def cena_abertura_etapa_8():
    print()
    print("=" * 60)
    print("🎬 INICIAR MISSÃO: O SISTEMA GANHA ENDEREÇO")
    print("=" * 60)
    print("Você chega a uma sala cheia de painéis verdes.")
    print()
    print("Até aqui, você já entendeu como o sistema nasce,")
    print("como ele guarda dados,")
    print("como a tela conversa com o backend,")
    print("como a interface aparece para o usuário,")
    print("como a segurança protege a entrada")
    print("e como o time registra mudanças com Git e GitHub.")
    print()
    print("Mas ainda existe uma pergunta importante:")
    print()
    print("como o sistema sai do computador do desenvolvedor")
    print("e fica disponível para pessoas usarem de verdade?")
    print()
    print("Gabriel aparece na tela e olha diretamente para você.")
    print()
    print("Olá. Eu sou Gabriel.")
    print()
    print("Minha área é Deploy.")
    print("Eu cuido do momento em que o sistema deixa de ser só código")
    print("e passa a estar disponível em um ambiente real.")
    print()
    print("Um sistema funcionando apenas no computador do dev")
    print("ainda não é um produto acessível.")
    print()
    print("Deploy é a passagem para o mundo real.")
    print()
    print("Nesta etapa, você vai entender:")
    print()
    print("- o que é um sistema local;")
    print("- o que significa fazer deploy;")
    print("- por que o sistema precisa de servidor;")
    print("- como domínio e DNS ajudam as pessoas a encontrar o sistema;")
    print("- o que são hospedagem, VPS e nuvem;")
    print("- como uma pipeline ajuda a publicar com segurança;")
    print("- e por que produção exige cuidado.")
    print()
    print("Gabriel aponta para o painel.")
    print()
    print("Sem decorar comando.")
    print("Sem sintaxe disfarçada.")
    print("Primeiro você entende a mudança de casa.")
    print("Depois, no mundo prático, aprende a operar a ferramenta.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def campo_treinamento_etapa_8():
    print()
    print("=" * 60)
    print("🛠️ CAMPO DE TREINAMENTO: A MUDANÇA DE CASA")
    print("=" * 60)
    print("Gabriel aparece na tela e olha diretamente para você.")
    print()
    print("Agora vamos acompanhar o caminho de um sistema saindo do computador do dev")
    print("e indo para um lugar onde outras pessoas conseguem acessar.")
    print()
    print("-" * 60)
    print("1. O SISTEMA FUNCIONA LOCALMENTE")
    print("-" * 60)
    print("No começo, o sistema funciona no computador de quem desenvolve.")
    print()
    print("Isso é útil para criar, testar e ajustar.")
    print()
    print("Mas o cliente não usa o computador do dev.")
    print()
    print("-" * 60)
    print("2. O SISTEMA PRECISA DE UMA CASA")
    print("-" * 60)
    print("Para outras pessoas acessarem, o sistema precisa morar em um servidor.")
    print()
    print("O servidor é o ambiente que fica disponível para receber acessos.")
    print()
    print("-" * 60)
    print("3. A MUDANÇA ACONTECE")
    print("-" * 60)
    print("Deploy é a mudança do sistema para esse ambiente acessível.")
    print()
    print("Antes, ele funcionava só localmente.")
    print("Depois, pode ser usado por usuários reais.")
    print()
    print("-" * 60)
    print("4. AS PESSOAS PRECISAM ENCONTRAR O SISTEMA")
    print("-" * 60)
    print("Um sistema no ar precisa de endereço.")
    print()
    print("O domínio é o nome fácil.")
    print("O DNS aponta esse nome para o servidor certo.")
    print()
    print("-" * 60)
    print("5. A PUBLICAÇÃO PRECISA DE CUIDADO")
    print("-" * 60)
    print("Em produção, pessoas reais podem estar usando o sistema.")
    print()
    print("Por isso, publicar mudança exige atenção.")
    print()
    print("Uma pipeline pode ajudar a conferir, testar e publicar com mais segurança.")
    print()
    print("-" * 60)
    print("RESUMO DO TREINAMENTO")
    print("-" * 60)
    print("Local é onde o dev cria e testa.")
    print("Servidor é onde o sistema pode morar.")
    print("Deploy é a mudança para um ambiente acessível.")
    print("Domínio é o nome fácil.")
    print("DNS aponta o nome para o servidor.")
    print("Pipeline ajuda a publicar com cuidado.")
    print("Produção é o mundo real do sistema.")
    print()
    print("Ideia de sobrevivência:")
    print("deploy transforma um sistema pronto em um sistema disponível.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def laboratorio_falhas_etapa_8():
    print()
    print("=" * 60)
    print("🧪 LABORATÓRIO DE FALHAS: QUANDO O SISTEMA NÃO SOBE")
    print("=" * 60)
    print("Gabriel aparece na tela e olha diretamente para você.")
    print()
    print("Agora vamos olhar falhas comuns no deploy.")
    print()
    print("A ideia não é decorar comando.")
    print("A ideia é entender onde a mudança pode quebrar.")
    print()
    print("-" * 60)
    print("FALHA 1 — FUNCIONA NA MINHA MÁQUINA")
    print("-" * 60)
    print("O sistema funciona no computador do dev,")
    print("mas não funciona no servidor.")
    print()
    print("Suspeita:")
    print("ambiente diferente ou configuração faltando.")
    print()
    print("Por quê?")
    print("O computador local e o servidor podem não estar preparados do mesmo jeito.")
    print()
    print("-" * 60)
    print("FALHA 2 — SISTEMA SEM ENDEREÇO")
    print("-" * 60)
    print("O sistema foi enviado para o servidor,")
    print("mas o usuário não consegue encontrar pelo nome do site.")
    print()
    print("Suspeita:")
    print("domínio ou DNS mal configurado.")
    print()
    print("Por quê?")
    print("O nome fácil precisa apontar para o servidor certo.")
    print()
    print("-" * 60)
    print("FALHA 3 — MUDANÇA QUEBRA EM PRODUÇÃO")
    print("-" * 60)
    print("Uma nova versão foi publicada e usuários reais começaram a ter problema.")
    print()
    print("Suspeita:")
    print("mudança publicada sem validação suficiente.")
    print()
    print("Por quê?")
    print("Produção exige cuidado porque afeta pessoas reais.")
    print()
    print("-" * 60)
    print("FALHA 4 — ESTEIRA PAROU")
    print("-" * 60)
    print("A pipeline tentou publicar, mas parou antes do fim.")
    print()
    print("Suspeita:")
    print("a esteira encontrou algo errado antes de chegar ao usuário.")
    print()
    print("Por quê?")
    print("Isso pode ser proteção, não defeito.")
    print("Melhor parar antes do cliente ser afetado.")
    print()
    print("-" * 60)
    print("IDEIA DE SOBREVIVÊNCIA")
    print("-" * 60)
    print("Deploy ruim pode derrubar uma experiência real.")
    print()
    print("Por isso, colocar no ar exige ambiente certo, endereço certo,")
    print("configuração correta e cuidado com produção.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def missao_producao_etapa_8():
    print()
    print("=" * 60)
    print("🏢 MISSÃO EM PRODUÇÃO: O SISTEMA NO AR")
    print("=" * 60)
    print("Gabriel aparece na tela e olha diretamente para você.")
    print()
    print("Agora o deploy sai do treinamento e entra em produção.")
    print()
    print("Imagine que a CampOne tem uma nova versão do app pronta.")
    print()
    print("-" * 60)
    print("CENA 1 — O CÓDIGO ESTÁ PRONTO")
    print("-" * 60)
    print("O time terminou uma melhoria.")
    print()
    print("A mudança foi registrada no Git.")
    print("O repositório está atualizado.")
    print()
    print("Mas isso ainda não significa que o cliente consegue usar.")
    print()
    print("-" * 60)
    print("CENA 2 — A ESTEIRA CONFERE")
    print("-" * 60)
    print("Antes de publicar, a pipeline pode conferir se está tudo em ordem.")
    print()
    print("Ela pode rodar verificações, preparar o ambiente e evitar improviso.")
    print()
    print("-" * 60)
    print("CENA 3 — O SISTEMA VAI PARA O SERVIDOR")
    print("-" * 60)
    print("A nova versão vai para o ambiente onde o sistema mora.")
    print()
    print("Esse ambiente precisa estar preparado para receber acessos.")
    print()
    print("-" * 60)
    print("CENA 4 — O ENDEREÇO APONTA PARA O LUGAR CERTO")
    print("-" * 60)
    print("O domínio precisa levar o usuário até o servidor correto.")
    print()
    print("O DNS ajuda nessa ligação entre nome fácil e endereço real.")
    print()
    print("-" * 60)
    print("CENA 5 — O USUÁRIO ACESSA")
    print("-" * 60)
    print("Agora o usuário abre o navegador e consegue usar a nova versão.")
    print()
    print("Se tudo deu certo, ele nem percebeu a mudança acontecendo.")
    print()
    print("-" * 60)
    print("IDEIA DE SOBREVIVÊNCIA")
    print("-" * 60)
    print("Deploy é o caminho entre código pronto e sistema usado por pessoas reais.")
    print()
    print("O objetivo não é só colocar na internet.")
    print("É colocar de um jeito seguro, estável e encontrável.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def prova_dominio_etapa_8():
    while True:
        print()
        print("=" * 60)
        print("✅ PROVA DE DOMÍNIO: O SISTEMA NO AR")
        print("=" * 60)
        print("Gabriel aparece na tela e olha diretamente para você.")
        print()
        print("A CampOne tem um sistema pronto no computador do dev,")
        print("envia para um servidor,")
        print("configura domínio e DNS,")
        print("usa uma pipeline")
        print("e publica para usuários reais.")
        print()
        print("PERGUNTA:")
        print("Qual leitura resume melhor esse caminho?")
        print()
        print("1 - O sistema só mudou de cor e continuou preso no computador do dev.")
        print("2 - O banco de dados decidiu sozinho publicar a aplicação.")
        print("3 - O sistema saiu do ambiente local, foi para um servidor, ganhou endereço e chegou à produção com cuidado.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "3":
            print()
            print("Gabriel confirma.")
            print('"Isso. Você juntou o caminho do deploy:"')
            print('"local, servidor, endereço, pipeline e produção."')
            print()
            print("A base teórica de Deploy está dominada.")
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Gabriel reancora com calma.")
            print('"Quase. Deploy não é mudança de cor."')
            print('"É disponibilizar o sistema."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "2":
            print()
            print("Gabriel aponta para o caminho do deploy.")
            print('"Boa tentativa, mas banco não publica sozinho."')
            print('"Deploy envolve ambiente, servidor, endereço e produção."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def registro_etapa_8():
    print()
    print("=" * 60)
    print("📝 REGISTRAR EXPERIÊNCIA — O SISTEMA NO AR")
    print("=" * 60)
    print("Gabriel aparece na tela e olha diretamente para você.")
    print()
    print("Vamos registrar o que você entendeu sobre deploy.")
    print()
    print("Você reconheceu que:")
    print()
    print("- sistema local é onde o dev cria e testa;")
    print("- deploy leva o sistema para um ambiente acessível;")
    print("- servidor é a casa onde o sistema fica disponível;")
    print("- domínio é o nome fácil que a pessoa digita;")
    print("- DNS aponta esse nome para o servidor correto;")
    print("- hospedagem, VPS e nuvem são formas de moradia do sistema;")
    print("- pipeline ajuda a publicar mudanças com mais segurança;")
    print("- produção é o ambiente usado por pessoas reais;")
    print("- deploy exige cuidado porque afeta usuários de verdade.")
    print()
    print("Gabriel confirma:")
    print()
    print("Isso ainda não é programação prática.")
    print("É visão de publicação.")
    print()
    print("Experiência registrada apenas na narrativa.")
    print("Salvamento real será criado em uma fase futura.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def relatorio_final_etapa_8():
    print()
    print("=" * 60)
    print("📋 RELATÓRIO FINAL — O SISTEMA NO AR")
    print("=" * 60)
    print("Gabriel aparece na tela e olha diretamente para você.")
    print()
    print("Relatório da missão: O Rito da Grande Implantação")
    print()
    print("Você agora sabe que:")
    print()
    print("- um sistema preso no computador do dev ainda não é produto disponível;")
    print("- deploy é colocar o sistema em funcionamento para usuários reais;")
    print("- servidor é onde o sistema fica disponível fora do ambiente local;")
    print("- domínio e DNS ajudam as pessoas a encontrar o sistema;")
    print("- hospedagem, VPS e nuvem são formas de dar moradia ao sistema;")
    print("- pipeline ajuda a levar mudanças para produção com cuidado;")
    print("- produção é o mundo real do sistema em uso;")
    print("- o melhor deploy é aquele que o usuário nem percebe.")
    print()
    print("Conclusão:")
    print()
    print("Deploy não é só colocar algo na internet.")
    print("É publicar com endereço, ambiente, cuidado e responsabilidade.")
    print()
    print("A etapa ainda não marca conclusão permanente nesta versão.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def entrar_etapa_8():
    while True:
        print()
        print("=" * 60)
        print("08. O RITO DA GRANDE IMPLANTAÇÃO")
        print("=" * 60)
        print("Tema real: Deploy")
        print("Tipo: Treinamento de Sobrevivência")
        print("Status: Estrutura inicial")
        print("Mentor previsto: Gabriel")
        print()
        print("CENTRO DE OPERAÇÕES")
        print("-" * 60)
        print("1 - Iniciar Missão")
        print("2 - Reconhecimento")
        print("3 - Campo de Treinamento")
        print("4 - Laboratório de Falhas")
        print("5 - Missão em Produção")
        print("6 - Prova de Domínio")
        print("7 - Registrar Experiência")
        print("8 - Relatório Final")
        print("0 - Retornar ao Nível 1")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            cena_abertura_etapa_8()
        elif escolha == "2":
            reconhecimento_etapa_8()
        elif escolha == "3":
            campo_treinamento_etapa_8()
        elif escolha == "4":
            laboratorio_falhas_etapa_8()
        elif escolha == "5":
            missao_producao_etapa_8()
        elif escolha == "6":
            prova_dominio_etapa_8()
        elif escolha == "7":
            registro_etapa_8()
        elif escolha == "8":
            relatorio_final_etapa_8()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")
