"""Etapa 07 — Dominando as Linhas do Tempo."""

def topico_git_etapa_7():
    while True:
        print()
        print("=" * 60)
        print('📘 TÓPICO 1: GIT')
        print("=" * 60)
        print('Git é como um caderno de mudanças do projeto.')
        print()
        print('Ele registra o que mudou, quando mudou e ajuda a voltar no histórico.')
        print()
        print('Richard aparece na tela e olha diretamente para você.')
        print()
        print('"Antes do Git, muita gente salvava versões no improviso:"')
        print('"arquivo final, final mesmo, final corrigido."')
        print()
        print('"Git nasceu para transformar bagunça em histórico organizado."')
        print()
        print('Ideia de sobrevivência:')
        print('Git guarda a história das mudanças do projeto.')
        print()
        print("PERGUNTA:")
        print('Por que o Git ajuda um projeto a não virar uma bagunça de arquivos')
        print('final, final2 e agora vai?')
        print()
        print('1 - Porque ele escolhe automaticamente qual tela do sistema fica mais bonita.')
        print('2 - Porque ele guarda a história das mudanças do projeto de forma organizada.')
        print('3 - Porque ele substitui o backend e o banco de dados.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Richard confirma.')
            print('"Isso. Git é o caderno da história do projeto."')
            print('"Ele ajuda o time a saber o que mudou, quando mudou e por quê."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Richard reancora com calma.')
            print('"Quase. Aparência da tela é outro assunto."')
            print('"Git não escolhe visual. Ele cuida da história das mudanças."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Richard aponta para a função do caderno.')
            print('"Boa tentativa, mas Git não substitui backend nem banco."')
            print('"Ele registra a evolução do projeto para o time entender o caminho."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_commit_etapa_7():
    while True:
        print()
        print("=" * 60)
        print('📸 TÓPICO 2: COMMIT')
        print("=" * 60)
        print('Commit é como uma fotografia de um momento do projeto.')
        print()
        print('Quando algo importante muda, o dev registra essa mudança.')
        print()
        print('Esse registro ajuda o time a entender o que foi feito e por quê.')
        print()
        print('Richard aponta para uma linha do tempo.')
        print()
        print('"Um commit não é só salvar."')
        print('"É deixar uma marca compreensível na história do projeto."')
        print()
        print('Ideia de sobrevivência:')
        print('commit registra uma mudança com sentido.')
        print()
        print("PERGUNTA:")
        print('Quando uma parte importante do projeto muda, por que o commit é útil?')
        print()
        print('1 - Porque ele registra uma mudança com sentido dentro da história do projeto.')
        print('2 - Porque ele apaga automaticamente todas as versões antigas sem perguntar.')
        print('3 - Porque ele muda a senha de todos os usuários do sistema.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            print()
            print('Richard confirma.')
            print('"Isso. Commit é uma fotografia com sentido."')
            print('"Ele deixa uma marca clara do que mudou no projeto."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '2':
            print()
            print('Richard reancora com calma.')
            print('"Quase. Commit não é uma borracha automática."')
            print('"Ele registra uma fotografia da mudança para o histórico continuar compreensível."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Richard separa os territórios.')
            print('"Boa tentativa, mas senha e acesso pertencem ao tema de segurança."')
            print('"Commit fala sobre registrar mudanças no projeto."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_branch_etapa_7():
    while True:
        print()
        print("=" * 60)
        print('🌿 TÓPICO 3: BRANCH')
        print("=" * 60)
        print('Às vezes o time precisa trabalhar sem mexer direto na versão principal.')
        print()
        print('Branch é uma linha separada de trabalho.')
        print()
        print('Ela permite testar, criar e ajustar sem colocar tudo em risco de imediato.')
        print()
        print('Richard desenha uma linha principal e uma linha lateral.')
        print()
        print('"A branch cria espaço para trabalhar com segurança."')
        print('"Depois, se fizer sentido, o trabalho volta para a linha principal."')
        print()
        print('Ideia de sobrevivência:')
        print('branch permite trabalhar sem bagunçar a versão principal.')
        print()
        print("PERGUNTA:")
        print('Por que uma branch ajuda quando alguém quer trabalhar sem mexer direto na versão principal?')
        print()
        print('1 - Porque branch é uma tela visual que substitui o frontend.')
        print('2 - Porque branch apaga a linha principal para começar tudo de novo.')
        print('3 - Porque branch cria uma linha separada de trabalho para testar e desenvolver com mais segurança.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '3':
            print()
            print('Richard confirma.')
            print('"Isso. Branch cria um espaço de trabalho separado."')
            print('"Assim o time pode testar ideias sem bagunçar a linha principal."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Richard reancora com calma.')
            print('"Quase. Branch não é uma tela."')
            print('"Ela é uma linha de trabalho dentro da história do projeto."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '2':
            print()
            print('Richard aponta para a linha principal.')
            print('"Boa tentativa, mas branch não serve para apagar a linha principal."')
            print('"Ela ajuda a trabalhar separado sem colocar a versão principal em risco."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_merge_conflito_etapa_7():
    while True:
        print()
        print("=" * 60)
        print('🔀 TÓPICO 4: MERGE E CONFLITO')
        print("=" * 60)
        print('Depois de trabalhar em uma branch, chega a hora de juntar mudanças.')
        print()
        print('Merge é o ato de juntar uma linha de trabalho com outra.')
        print()
        print('Mas se duas pessoas mexeram no mesmo ponto, o Git pode parar e avisar.')
        print()
        print('Esse aviso é um conflito.')
        print()
        print('Richard levanta a mão com calma.')
        print()
        print('"Conflito não significa que alguém errou."')
        print('"Significa que o Git precisa de uma decisão humana."')
        print()
        print('Ideia de sobrevivência:')
        print('merge junta mudanças; conflito pede escolha cuidadosa.')
        print()
        print("PERGUNTA:")
        print('Quando duas mudanças precisam ser juntadas, mas mexeram no mesmo ponto,')
        print('o que o conflito indica?')
        print()
        print('1 - Que o projeto deve ser apagado e recomeçado do zero.')
        print('2 - Que o Git precisa de uma decisão humana para resolver aquela parte.')
        print('3 - Que o banco de dados escolheu sozinho qual versão fica.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Richard confirma.')
            print('"Isso. Conflito não significa que alguém errou."')
            print('"Significa que o Git parou para o time decidir com segurança."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Richard reancora com calma.')
            print('"Quase. Conflito não é fim do projeto."')
            print('"É um aviso de que aquela parte precisa ser analisada com cuidado."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Richard aponta para o time.')
            print('"Boa tentativa, mas banco de dados não resolve conflito de código."')
            print('"Quem decide como juntar mudanças é o time."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_github_etapa_7():
    while True:
        print()
        print("=" * 60)
        print('☁️ TÓPICO 5: GITHUB')
        print("=" * 60)
        print('Git guarda a história do projeto.')
        print('Mas o time também precisa compartilhar essa história.')
        print()
        print('GitHub é um lugar na internet onde o repositório pode ficar guardado.')
        print()
        print('Ele ajuda o time a colaborar, revisar e acessar o projeto de outros lugares.')
        print()
        print('Richard aponta para um repositório online.')
        print()
        print('"Git é o caderno."')
        print('"GitHub é o lugar onde esse caderno pode ficar disponível para o time."')
        print()
        print('Ideia de sobrevivência:')
        print('GitHub ajuda o time a compartilhar e colaborar no projeto.')
        print()
        print("PERGUNTA:")
        print('Se Git é o caderno da história do projeto, qual é o papel do GitHub?')
        print()
        print('1 - Ajudar o time a guardar, compartilhar e colaborar nesse caderno pela internet.')
        print('2 - Escolher sozinho quais pessoas podem entrar no sistema da empresa.')
        print('3 - Criar automaticamente o layout visual das telas.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            print()
            print('Richard confirma.')
            print('"Isso. GitHub é onde o caderno do projeto pode ficar disponível para o time."')
            print('"Ele ajuda na colaboração, revisão e acesso ao histórico."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '2':
            print()
            print('Richard reancora com calma.')
            print('"Quase. Permissão de acesso ao sistema pertence ao tema de segurança."')
            print('"GitHub ajuda o time a colaborar no projeto."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Richard separa ferramenta de colaboração e tela.')
            print('"Boa tentativa, mas layout visual pertence ao frontend."')
            print('"GitHub não desenha tela. Ele ajuda a compartilhar o repositório."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_clone_push_pull_etapa_7():
    while True:
        print()
        print("=" * 60)
        print('🔁 TÓPICO 6: CLONE, PUSH E PULL')
        print("=" * 60)
        print('Quando o projeto está em um repositório online, o time precisa trocar mudanças.')
        print()
        print('Clone é pegar uma cópia do projeto pela primeira vez.')
        print('Push é empurrar suas mudanças para o repositório online.')
        print('Pull é puxar as mudanças que outras pessoas enviaram.')
        print()
        print('Richard mostra o caminho de ida e volta.')
        print()
        print('"Clone acontece quando você traz o projeto para sua máquina."')
        print('"Push envia sua parte."')
        print('"Pull atualiza sua cópia com o que o time fez."')
        print()
        print('Ideia de sobrevivência:')
        print('clone traz, push envia, pull atualiza.')
        print()
        print("PERGUNTA:")
        print('Qual leitura combina melhor com clone, push e pull no trabalho em equipe?')
        print()
        print('1 - Clone apaga o projeto, push troca as cores e pull muda a senha.')
        print('2 - Clone cria uma tela nova, push abre o banco e pull fecha o servidor.')
        print('3 - Clone traz uma cópia, push envia suas mudanças e pull atualiza sua cópia com o que o time enviou.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '3':
            print()
            print('Richard confirma.')
            print('"Isso. Clone traz, push envia e pull atualiza."')
            print('"São movimentos de ida e volta do caderno do time."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Richard reancora com calma.')
            print('"Quase. Esses termos não falam de cor, senha ou apagar projeto."')
            print('"Eles falam de trazer, enviar e atualizar trabalho."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '2':
            print()
            print('Richard aponta para o movimento do projeto.')
            print('"Boa tentativa, mas isso mistura várias áreas."')
            print('"Clone, push e pull são movimentos do projeto entre sua máquina e o repositório."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_historico_etapa_7():
    while True:
        print()
        print("=" * 60)
        print('🕰️ TÓPICO 7: HISTÓRICO DO PROJETO')
        print("=" * 60)
        print('Um projeto real cresce com muitas mudanças.')
        print()
        print('O histórico mostra como ele evoluiu.')
        print()
        print('Ele ajuda a descobrir quando algo nasceu, quando algo quebrou')
        print('e quem participou de cada mudança.')
        print()
        print('Richard abre uma linha do tempo.')
        print()
        print('"O histórico é uma memória organizada do trabalho do time."')
        print('"Sem ele, todo problema vira adivinhação."')
        print()
        print('Ideia de sobrevivência:')
        print('histórico ajuda a investigar e entender a evolução do projeto.')
        print()
        print("PERGUNTA:")
        print('Quando aparece um bug que talvez tenha começado semanas atrás,')
        print('por que o histórico do projeto ajuda?')
        print()
        print('1 - Porque ele muda automaticamente o design da tela.')
        print('2 - Porque ele mostra a sequência de mudanças e ajuda a investigar quando algo nasceu ou quebrou.')
        print('3 - Porque ele impede qualquer pessoa de trabalhar no projeto.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Richard confirma.')
            print('"Isso. Histórico evita adivinhação."')
            print('"Ele mostra o caminho que o projeto percorreu até chegar ao estado atual."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Richard reancora com calma.')
            print('"Quase. Design da tela é tema de frontend."')
            print('"Histórico ajuda a investigar a evolução do projeto."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Richard aponta para o rastro do trabalho.')
            print('"Boa tentativa, mas histórico não existe para impedir trabalho."')
            print('"Ele existe para deixar rastros claros do que aconteceu."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_git_github_time_etapa_7():
    while True:
        print()
        print("=" * 60)
        print('🤝 TÓPICO 8: GIT E GITHUB NO TIME')
        print("=" * 60)
        print('Git e GitHub não existem só para guardar código.')
        print()
        print('Eles ajudam pessoas a trabalharem juntas sem se perderem.')
        print()
        print('Cada pessoa pode trabalhar, registrar, enviar, atualizar e revisar.')
        print()
        print('Richard olha diretamente para você.')
        print()
        print('"No trabalho real, não basta fazer alteração."')
        print('"É preciso deixar rastro, conversar com o time e manter o projeto organizado."')
        print()
        print('Ideia de sobrevivência:')
        print('Git e GitHub são ferramentas de colaboração e memória do projeto.')
        print()
        print("PERGUNTA:")
        print('No trabalho real, por que Git e GitHub são importantes para o time?')
        print()
        print('1 - Porque ajudam a registrar, compartilhar, revisar e organizar mudanças do projeto.')
        print('2 - Porque substituem todas as conversas entre pessoas da equipe.')
        print('3 - Porque fazem o sistema entrar automaticamente em produção sem revisão.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            print()
            print('Richard confirma.')
            print('"Isso. Git e GitHub ajudam o time a trabalhar com memória e organização."')
            print('"Cada mudança ganha rastro e o projeto fica mais fácil de cuidar."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '2':
            print()
            print('Richard reancora com calma.')
            print('"Quase. Git e GitHub ajudam a colaboração, mas não substituem conversa."')
            print('"O time ainda precisa tomar decisões e se comunicar."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Richard separa colaboração de publicação.')
            print('"Boa tentativa, mas publicar sistema é outro assunto."')
            print('"Git e GitHub ajudam no histórico e colaboração; deploy vem em outra etapa."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def reconhecimento_etapa_7():
    while True:
        print()
        print("=" * 60)
        print("💡 RECONHECIMENTO: O CADERNO DO TIME")
        print("=" * 60)
        print("Richard organiza os primeiros conceitos de Git e GitHub.")
        print()
        print("1 - Git")
        print("2 - Commit")
        print("3 - Branch")
        print("4 - Merge e conflito")
        print("5 - GitHub")
        print("6 - Clone, Push e Pull")
        print("7 - Histórico do projeto")
        print("8 - Git e GitHub no time")
        print("0 - Voltar à etapa 07")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            topico_git_etapa_7()
        elif escolha == "2":
            topico_commit_etapa_7()
        elif escolha == "3":
            topico_branch_etapa_7()
        elif escolha == "4":
            topico_merge_conflito_etapa_7()
        elif escolha == "5":
            topico_github_etapa_7()
        elif escolha == "6":
            topico_clone_push_pull_etapa_7()
        elif escolha == "7":
            topico_historico_etapa_7()
        elif escolha == "8":
            topico_git_github_time_etapa_7()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")


def cena_abertura_etapa_7():
    print()
    print("=" * 60)
    print("🎬 INICIAR MISSÃO: O CADERNO DO TIME")
    print("=" * 60)
    print("Você chega a uma sala com um quadro cheio de linhas e marcas de tempo.")
    print()
    print("Depois de entender a rede, o backend, o banco, a ponte, a interface e a portaria,")
    print("agora falta entender como um time registra a evolução de um projeto.")
    print()
    print("Richard aparece na tela e olha diretamente para você.")
    print()
    print("Olá. Eu sou Richard.")
    print()
    print("Minha área é Git e GitHub.")
    print("Eu ajudo o time a guardar a história do projeto sem se perder.")
    print()
    print("Antes do Git, muita gente salvava arquivos no improviso:")
    print("projeto_final, projeto_final_corrigido, projeto_final_agora_vai.")
    print()
    print("Isso não conta a história de verdade.")
    print()
    print("Git existe para registrar mudanças com ordem, contexto e memória.")
    print()
    print("Nesta etapa, você vai entender:")
    print()
    print("- por que um projeto precisa de histórico;")
    print("- o que é Git;")
    print("- o que é commit;")
    print("- por que branches ajudam a trabalhar com segurança;")
    print("- como mudanças são juntadas;")
    print("- por que conflitos não são necessariamente erro;")
    print("- para que serve o GitHub;")
    print("- e como clone, push e pull fazem o time trabalhar junto.")
    print()
    print("Richard aponta para a linha do tempo.")
    print()
    print("Sem decorar comandos.")
    print("Sem sintaxe disfarçada.")
    print("Primeiro você entende o caderno.")
    print("Depois, no mundo prático, aprende a operar a ferramenta.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def campo_treinamento_etapa_7():
    print()
    print("=" * 60)
    print("🛠️ CAMPO DE TREINAMENTO: LENDO O CADERNO")
    print("=" * 60)
    print("Richard aparece na tela e olha diretamente para você.")
    print()
    print("Agora vamos acompanhar como um projeto cresce com histórico.")
    print()
    print("Imagine o app da CampOne nascendo aos poucos.")
    print()
    print("-" * 60)
    print("1. O PROJETO COMEÇA")
    print("-" * 60)
    print("No começo, existe apenas a estrutura básica.")
    print()
    print("O time registra essa primeira fotografia do projeto.")
    print()
    print("Essa fotografia é um commit.")
    print()
    print("-" * 60)
    print("2. UMA FUNCIONALIDADE NASCE")
    print("-" * 60)
    print("Depois, alguém cria uma tela de reservas.")
    print()
    print("Essa mudança também precisa entrar no histórico.")
    print()
    print("O commit ajuda o time a saber o que mudou e por quê.")
    print()
    print("-" * 60)
    print("3. UM PROBLEMA É CORRIGIDO")
    print("-" * 60)
    print("Mais tarde, aparece um erro no cálculo de uma reserva.")
    print()
    print("O time corrige o problema e registra a correção.")
    print()
    print("Sem histórico, seria difícil descobrir quando o problema apareceu.")
    print()
    print("-" * 60)
    print("4. ALGUÉM TRABALHA EM UMA LINHA SEPARADA")
    print("-" * 60)
    print("Para não mexer direto na versão principal, uma pessoa trabalha em uma branch.")
    print()
    print("A branch permite testar uma ideia sem colocar a linha principal em risco.")
    print()
    print("-" * 60)
    print("5. O TIME JUNTA AS MUDANÇAS")
    print("-" * 60)
    print("Quando o trabalho faz sentido, ele pode ser juntado de volta.")
    print()
    print("Essa junção é o merge.")
    print()
    print("Se duas pessoas mexeram no mesmo lugar, pode aparecer conflito.")
    print("Conflito não é drama: é o Git pedindo uma decisão humana.")
    print()
    print("-" * 60)
    print("RESUMO DO TREINAMENTO")
    print("-" * 60)
    print("Git guarda a história.")
    print("Commit registra uma mudança.")
    print("Branch cria uma linha segura de trabalho.")
    print("Merge junta mudanças.")
    print("Conflito pede decisão.")
    print("GitHub ajuda o time a compartilhar o caderno.")
    print()
    print("Ideia de sobrevivência:")
    print("um projeto profissional precisa de memória, não de adivinhação.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def laboratorio_falhas_etapa_7():
    print()
    print("=" * 60)
    print("🧪 LABORATÓRIO DE FALHAS: PROBLEMAS NO CADERNO")
    print("=" * 60)
    print("Richard aparece na tela e olha diretamente para você.")
    print()
    print("Agora vamos olhar falhas comuns no trabalho com Git e GitHub.")
    print()
    print("A ideia não é decorar comando.")
    print("A ideia é entender o sintoma e suspeitar da peça certa.")
    print()
    print("-" * 60)
    print("FALHA 1 — MUDANÇA SEM REGISTRO")
    print("-" * 60)
    print("A pessoa alterou o projeto, mas não registrou a mudança.")
    print()
    print("Suspeita:")
    print("faltou commit.")
    print()
    print("Por quê?")
    print("Sem commit, a mudança não vira uma fotografia clara no histórico.")
    print()
    print("-" * 60)
    print("FALHA 2 — TRABALHO FICOU SÓ NO COMPUTADOR")
    print("-" * 60)
    print("A pessoa registrou a mudança, mas o time não consegue ver.")
    print()
    print("Suspeita:")
    print("faltou push.")
    print()
    print("Por quê?")
    print("O commit ficou local, mas ainda não foi enviado para o repositório online.")
    print()
    print("-" * 60)
    print("FALHA 3 — PROJETO LOCAL DESATUALIZADO")
    print("-" * 60)
    print("O time mudou o projeto, mas a pessoa continua trabalhando em uma cópia antiga.")
    print()
    print("Suspeita:")
    print("faltou pull.")
    print()
    print("Por quê?")
    print("A cópia local precisa puxar as mudanças que já foram enviadas pelo time.")
    print()
    print("-" * 60)
    print("FALHA 4 — DUAS PESSOAS MEXERAM NO MESMO PONTO")
    print("-" * 60)
    print("Na hora de juntar mudanças, o Git para e avisa que existe conflito.")
    print()
    print("Suspeita:")
    print("as mudanças precisam de decisão humana.")
    print()
    print("Por quê?")
    print("O Git não deve escolher sozinho quando duas versões mexem no mesmo lugar.")
    print()
    print("-" * 60)
    print("IDEIA DE SOBREVIVÊNCIA")
    print("-" * 60)
    print("Git não existe para impedir o trabalho.")
    print()
    print("Ele existe para deixar rastros claros,")
    print("evitar adivinhação")
    print("e ajudar o time a trabalhar sem apagar o caminho.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def missao_producao_etapa_7():
    print()
    print("=" * 60)
    print("🏢 MISSÃO EM PRODUÇÃO: O TIME TRABALHANDO JUNTO")
    print("=" * 60)
    print("Richard aparece na tela e olha diretamente para você.")
    print()
    print("Agora o caderno do time sai do treinamento e entra em produção.")
    print()
    print("Imagine que a equipe da CampOne está trabalhando no mesmo app.")
    print()
    print("-" * 60)
    print("CENA 1 — UMA PESSOA COMEÇA NO PROJETO")
    print("-" * 60)
    print("Ela precisa trazer uma cópia do projeto para a própria máquina.")
    print()
    print("Essa primeira cópia é a ideia do clone.")
    print()
    print("-" * 60)
    print("CENA 2 — UMA FUNCIONALIDADE É CRIADA")
    print("-" * 60)
    print("A pessoa trabalha em uma nova tela.")
    print()
    print("Quando termina uma parte importante, registra a mudança com commit.")
    print()
    print("O commit deixa claro o que mudou.")
    print()
    print("-" * 60)
    print("CENA 3 — A MUDANÇA PRECISA CHEGAR AO TIME")
    print("-" * 60)
    print("Depois de registrar, a pessoa envia sua parte para o repositório online.")
    print()
    print("Essa é a ideia do push.")
    print()
    print("-" * 60)
    print("CENA 4 — O TIME TAMBÉM MUDOU COISAS")
    print("-" * 60)
    print("Antes de continuar trabalhando, a pessoa precisa atualizar sua cópia.")
    print()
    print("Essa é a ideia do pull.")
    print()
    print("-" * 60)
    print("CENA 5 — MUDANÇAS SE ENCONTRAM")
    print("-" * 60)
    print("Quando linhas de trabalho se juntam, pode acontecer merge.")
    print()
    print("Se duas mudanças baterem no mesmo ponto, pode aparecer conflito.")
    print()
    print("O conflito pede conversa e decisão do time.")
    print()
    print("-" * 60)
    print("IDEIA DE SOBREVIVÊNCIA")
    print("-" * 60)
    print("No trabalho real, Git e GitHub ajudam o time a não depender de memória solta.")
    print()
    print("Cada mudança ganha registro.")
    print("Cada pessoa consegue enviar e receber trabalho.")
    print("Cada problema pode ser investigado no histórico.")
    print()
    print("Um bom dev não só altera o projeto.")
    print("Ele deixa o caminho compreensível para o time.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def prova_dominio_etapa_7():
    while True:
        print()
        print("=" * 60)
        print("✅ PROVA DE DOMÍNIO: O CADERNO DO TIME")
        print("=" * 60)
        print("Richard aparece na tela e olha diretamente para você.")
        print()
        print('"Agora vamos juntar o caderno inteiro em uma cena só."')
        print()
        print("Um dev cria uma mudança em uma branch,")
        print("registra com commit,")
        print("envia para o GitHub,")
        print("atualiza a própria cópia com o que o time fez")
        print("e encontra um conflito ao juntar mudanças.")
        print()
        print("PERGUNTA:")
        print("Qual leitura mostra melhor o que aconteceu?")
        print()
        print("1 - O banco de dados decidiu sozinho que a mudança era inválida.")
        print("2 - O frontend apagou a tela porque o botão foi clicado errado.")
        print("3 - O dev trabalhou em uma linha separada, registrou a mudança, compartilhou no repositório, atualizou a cópia local e encontrou uma parte que precisa de decisão humana.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "3":
            print()
            print("Richard confirma.")
            print('"Isso. Você juntou o caderno do time:"')
            print('"branch, commit, GitHub, push, pull e conflito."')
            print()
            print("A base teórica de Git e GitHub está dominada.")
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Richard reancora com calma.")
            print('"Quase. Banco de dados não decide conflito de histórico do projeto."')
            print('"Aqui estamos falando de Git, GitHub e colaboração."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "2":
            print()
            print("Richard aponta para o caderno do time.")
            print('"Boa tentativa, mas isso não é problema de tela."')
            print('"O conflito apareceu porque mudanças do projeto precisam ser combinadas."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def registro_etapa_7():
    print()
    print("=" * 60)
    print("📝 REGISTRAR EXPERIÊNCIA — O CADERNO DO TIME")
    print("=" * 60)
    print("Richard aparece na tela e olha diretamente para você.")
    print()
    print("Vamos registrar o que você entendeu sobre Git e GitHub.")
    print()
    print("Você reconheceu que:")
    print()
    print("- Git guarda a história das mudanças do projeto;")
    print("- commit registra uma mudança com sentido;")
    print("- branch cria uma linha segura de trabalho;")
    print("- merge junta mudanças;")
    print("- conflito pede decisão humana;")
    print("- GitHub ajuda o time a compartilhar o repositório;")
    print("- clone traz uma cópia do projeto;")
    print("- push envia mudanças;")
    print("- pull atualiza sua cópia local;")
    print("- histórico ajuda a investigar a evolução do projeto.")
    print()
    print("Richard confirma:")
    print()
    print("Isso ainda não é programação prática.")
    print("É visão de trabalho em equipe.")
    print()
    print("Experiência registrada apenas na narrativa.")
    print("Salvamento real será criado em uma fase futura.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def relatorio_final_etapa_7():
    print()
    print("=" * 60)
    print("📋 RELATÓRIO FINAL — O CADERNO DO TIME")
    print("=" * 60)
    print("Richard aparece na tela e olha diretamente para você.")
    print()
    print("Relatório da missão: Dominando as Linhas do Tempo")
    print()
    print("Você agora sabe que:")
    print()
    print("- Git é o caderno de mudanças do projeto;")
    print("- commits registram momentos importantes;")
    print("- branches permitem trabalhar sem mexer direto na linha principal;")
    print("- merge junta linhas de trabalho;")
    print("- conflitos não são desastre, são pedidos de decisão;")
    print("- GitHub ajuda o time a colaborar pela internet;")
    print("- clone, push e pull movem o projeto entre sua máquina e o repositório;")
    print("- o histórico evita adivinhação quando algo quebra.")
    print()
    print("Conclusão:")
    print()
    print("Você começou a enxergar que um projeto profissional precisa de memória.")
    print()
    print("Não basta alterar.")
    print("É preciso deixar rastro, contexto e caminho para o time.")
    print()
    print("A etapa ainda não marca conclusão permanente nesta versão.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def entrar_etapa_7():
    while True:
        print()
        print("=" * 60)
        print("07. DOMINANDO AS LINHAS DO TEMPO")
        print("=" * 60)
        print("Tema real: Git e GitHub")
        print("Tipo: Treinamento de Sobrevivência")
        print("Status: Estrutura inicial")
        print("Mentor previsto: Richard")
        print()
        print("CENTRO DE OPERAÇÕES")
        print("-" * 60)
        print("1 - Iniciar Missão")
        print("2 - Reconhecimento")
        print("3 - Campo de Treinamento")
        print("4 - Laboratório de Falhas")
        print("5 - Missão em Produção")
        print("6 - Prova de Domínio")
        print("7 - Registrar Experiência")
        print("8 - Relatório Final")
        print("0 - Retornar ao Nível 1")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            cena_abertura_etapa_7()
        elif escolha == "2":
            reconhecimento_etapa_7()
        elif escolha == "3":
            campo_treinamento_etapa_7()
        elif escolha == "4":
            laboratorio_falhas_etapa_7()
        elif escolha == "5":
            missao_producao_etapa_7()
        elif escolha == "6":
            prova_dominio_etapa_7()
        elif escolha == "7":
            registro_etapa_7()
        elif escolha == "8":
            relatorio_final_etapa_7()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")
