"""Etapa 05 — Forjando a Interface Visual."""

def topico_frontend_etapa_5():
    while True:
        print()
        print("=" * 60)
        print('🖥️ TÓPICO 1: O QUE É FRONTEND')
        print("=" * 60)
        print('Frontend é a parte do sistema que o usuário vê e usa.')
        print()
        print('É a tela, os botões, os textos, as imagens, os campos e as interações.')
        print()
        print('Irlene aparece na tela e olha diretamente para você.')
        print()
        print('"Se o backend trabalha por trás, o frontend olha para o usuário."')
        print('"Ele precisa ser claro, organizado e fácil de usar."')
        print()
        print('Ideia de sobrevivência:')
        print('frontend é a frente visível do sistema.')
        print()
        print("PERGUNTA:")
        print('O que melhor descreve o frontend em um sistema?')
        print()
        print('1 - A parte escondida que processa regras e conversa com o banco de dados.')
        print('2 - A parte que o usuário vê, toca e usa: telas, botões, textos, campos e interações.')
        print('3 - O lugar onde os dados ficam guardados de forma organizada.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Irlene confirma.')
            print('"Isso. Frontend é a parte visível do sistema."')
            print('"É onde o usuário encontra a experiência de uso."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Irlene reancora com calma.')
            print('"Quase. Essa descrição combina mais com o backend, que trabalha por trás."')
            print('"Frontend é a parte visível, aquela que o usuário realmente usa na tela."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Irlene aponta para a separação das partes.')
            print('"Boa tentativa. Guardar dados é papel do banco de dados."')
            print('"Frontend é a frente visível do sistema, onde a pessoa lê, clica e interage."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_html_etapa_5():
    while True:
        print()
        print("=" * 60)
        print('🏗️ TÓPICO 2: HTML — ESTRUTURA DA PÁGINA')
        print("=" * 60)
        print('Antes de uma tela ficar bonita ou interativa, ela precisa existir.')
        print()
        print('O HTML organiza o que aparece na página:')
        print('títulos, textos, imagens, botões, links e campos.')
        print()
        print('Irlene aponta para uma tela simples.')
        print()
        print('"Pensa assim: primeiro a página precisa dizer o que existe nela."')
        print('"Depois outras partes cuidam da aparência e do comportamento."')
        print()
        print('Ideia de sobrevivência:')
        print('HTML define a estrutura do que existe na tela.')
        print()
        print("PERGUNTA:")
        print('Antes de uma tela ganhar cor, estilo ou reação,')
        print('ela precisa dizer o que existe nela. Qual peça faz esse papel?')
        print()
        print('1 - CSS, porque ele decide as cores e os espaços da tela.')
        print('2 - JavaScript, porque ele faz a tela reagir aos cliques.')
        print('3 - HTML, porque ele organiza a estrutura: títulos, textos, imagens, botões e campos.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '3':
            print()
            print('Irlene confirma.')
            print('"Isso. HTML é a estrutura."')
            print('"Ele diz quais peças existem na página."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Irlene reancora com calma.')
            print('"Quase. CSS cuida da aparência visual."')
            print('"Mas antes de pintar ou organizar visualmente, a tela precisa ter estrutura."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '2':
            print()
            print('Irlene aponta para a ordem das peças.')
            print('"Boa tentativa. JavaScript entra quando a tela precisa reagir."')
            print('"Mas primeiro a tela precisa saber quais peças existem nela."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_css_etapa_5():
    while True:
        print()
        print("=" * 60)
        print('🎨 TÓPICO 3: CSS — APARÊNCIA VISUAL')
        print("=" * 60)
        print('Depois que a estrutura existe, a tela precisa ganhar forma visual.')
        print()
        print('O CSS cuida da aparência:')
        print('cores, tamanhos, espaçamentos, fontes e organização visual.')
        print()
        print('Irlene mostra a mesma tela com e sem estilo.')
        print()
        print('"Sem aparência, a informação até existe, mas fica difícil de usar."')
        print('"Com estilo, a tela ganha clareza, identidade e conforto."')
        print()
        print('Ideia de sobrevivência:')
        print('CSS dá forma visual ao que o HTML colocou na tela.')
        print()
        print("PERGUNTA:")
        print('Uma tela tem título, imagem, botão e campo,')
        print('mas está sem cor, sem espaçamento e difícil de ler.')
        print('Qual peça provavelmente está faltando ou falhando?')
        print()
        print('1 - CSS, porque ele cuida da aparência visual e da organização da tela.')
        print('2 - HTML, porque ele apaga todos os dados quando a tela fica sem cor.')
        print('3 - Banco de Dados, porque cor e espaçamento ficam guardados em tabelas.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            print()
            print('Irlene confirma.')
            print('"Isso. CSS dá forma visual ao que já existe na tela."')
            print('"Ele ajuda a tela ficar clara, organizada e confortável."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '2':
            print()
            print('Irlene reancora com calma.')
            print('"Quase. HTML ajuda a estrutura existir."')
            print('"Se tudo aparece, mas está feio ou desorganizado, a estrutura provavelmente está lá."')
            print('"O problema aponta mais para a aparência."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Irlene aponta para a diferença entre dados e visual.')
            print('"Boa tentativa. Banco de dados guarda informações."')
            print('"Cor, espaçamento e organização visual pertencem à interface, não à despensa dos dados."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_javascript_etapa_5():
    while True:
        print()
        print("=" * 60)
        print('⚡ TÓPICO 4: JAVASCRIPT — COMPORTAMENTO DA TELA')
        print("=" * 60)
        print('Uma tela não precisa apenas aparecer.')
        print('Ela também precisa reagir ao usuário.')
        print()
        print('JavaScript entra quando algo precisa acontecer:')
        print('clicar, abrir, fechar, validar, mudar ou responder sem recarregar tudo.')
        print()
        print('Irlene toca em um botão da tela.')
        print()
        print('"Quando a tela reage ao seu clique, existe comportamento acontecendo."')
        print('"Essa é a parte viva da interface."')
        print()
        print('Ideia de sobrevivência:')
        print('JavaScript faz a tela reagir.')
        print()
        print("PERGUNTA:")
        print('A tela aparece bonita, mas o botão não responde quando o usuário clica.')
        print('Qual peça é a principal suspeita?')
        print()
        print('1 - CSS, porque ele sempre cria todas as reações da tela.')
        print('2 - JavaScript, porque ele adiciona comportamento e faz a tela reagir.')
        print('3 - HTML, porque ele guarda a senha do usuário.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Irlene confirma.')
            print('"Isso. JavaScript é a parte que faz a tela reagir."')
            print('"Ele transforma uma tela parada em uma interface viva."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Irlene reancora com calma.')
            print('"Quase. CSS cuida da aparência."')
            print('"Se a tela está bonita, mas nada reage, o problema não parece estar na pintura da tela."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Irlene aponta para a função de cada peça.')
            print('"Boa tentativa. HTML organiza o que existe na página."')
            print('"Mas reação ao clique é comportamento."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_dom_etapa_5():
    while True:
        print()
        print("=" * 60)
        print('🧩 TÓPICO 5: DOM — MAPA VIVO DA PÁGINA')
        print("=" * 60)
        print('Para mudar uma parte da tela, o sistema precisa encontrar essa parte.')
        print()
        print('O DOM é como um mapa vivo da página.')
        print('Ele permite que a tela encontre um botão, um texto, uma imagem ou um campo específico.')
        print()
        print('Irlene aponta para vários botões parecidos.')
        print()
        print('"Se existem dez botões, a tela precisa saber exatamente qual foi clicado."')
        print('"O DOM ajuda a encontrar a peça certa."')
        print()
        print('Ideia de sobrevivência:')
        print('DOM é o mapa que permite mexer em partes específicas da tela.')
        print()
        print("PERGUNTA:")
        print('Se existem dez botões parecidos na tela,')
        print('como o sistema consegue mexer só no botão que foi clicado?')
        print()
        print('1 - Ele muda todos os botões ao mesmo tempo, porque não consegue saber qual foi clicado.')
        print('2 - Ele pede ao banco de dados para escolher um botão aleatório.')
        print('3 - Ele usa o DOM como um mapa vivo da página para encontrar a peça certa.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '3':
            print()
            print('Irlene confirma.')
            print('"Isso. O DOM funciona como um mapa vivo da página."')
            print('"Ele ajuda a encontrar e alterar uma parte específica da tela."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Irlene reancora com calma.')
            print('"Quase. Se a tela mudasse tudo ao mesmo tempo, a experiência ficaria confusa."')
            print('"O sistema precisa localizar a peça certa."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '2':
            print()
            print('Irlene aponta para a própria página.')
            print('"Boa tentativa. O banco guarda dados, mas não escolhe botão visual na tela."')
            print('"Essa busca pela peça certa acontece dentro da própria página."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_responsividade_etapa_5():
    while True:
        print()
        print("=" * 60)
        print('📱 TÓPICO 6: RESPONSIVIDADE — TELA QUE SE ADAPTA')
        print("=" * 60)
        print('O usuário pode abrir o sistema no computador, tablet ou celular.')
        print()
        print('A tela precisa se reorganizar para continuar fácil de usar.')
        print()
        print('Responsividade é essa capacidade de adaptação.')
        print()
        print('Irlene coloca duas telas lado a lado.')
        print()
        print('"No computador, há mais espaço."')
        print('"No celular, tudo precisa se ajustar sem quebrar."')
        print()
        print('Ideia de sobrevivência:')
        print('uma interface boa se adapta ao tamanho da tela.')
        print()
        print("PERGUNTA:")
        print('Por que uma tela precisa se adaptar ao celular, tablet e computador?')
        print()
        print('1 - Porque a mesma interface precisa continuar clara e fácil de usar em tamanhos diferentes.')
        print('2 - Porque o celular sempre apaga o backend quando abre uma página.')
        print('3 - Porque responsividade serve apenas para trocar a senha do usuário.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            print()
            print('Irlene confirma.')
            print('"Isso. Uma boa interface se reorganiza conforme o espaço disponível."')
            print('"Ela precisa funcionar bem no computador e no celular."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '2':
            print()
            print('Irlene reancora com calma.')
            print('"Quase. O tamanho da tela não apaga o backend."')
            print('"O problema aqui é visual: a interface precisa caber e continuar usável."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Irlene aponta para outro território.')
            print('"Boa tentativa, mas senha e acesso pertencem ao tema de segurança."')
            print('"Responsividade fala sobre adaptação da tela."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_frontend_completo_etapa_5():
    while True:
        print()
        print("=" * 60)
        print('🧠 TÓPICO 7: FRONTEND COMPLETO')
        print("=" * 60)
        print('Agora juntamos as peças da interface visual.')
        print()
        print('HTML coloca a estrutura.')
        print('CSS cuida da aparência.')
        print('JavaScript adiciona comportamento.')
        print('DOM ajuda a encontrar e alterar partes da tela.')
        print('Responsividade faz tudo se adaptar ao dispositivo.')
        print()
        print('Irlene olha diretamente para você.')
        print()
        print('"Frontend não é só deixar bonito."')
        print('"É fazer a tela existir, ser clara, reagir e funcionar bem para quem usa."')
        print()
        print('Ideia de sobrevivência:')
        print('frontend é a experiência visível do sistema funcionando.')
        print()
        print("PERGUNTA:")
        print('Qual conjunto representa melhor uma interface visual funcionando bem?')
        print()
        print('1 - Só cores bonitas, mesmo que nada esteja organizado ou funcionando.')
        print('2 - Estrutura, aparência, comportamento, localização das peças e adaptação ao tamanho da tela.')
        print('3 - Apenas banco de dados e servidor, sem tela para o usuário.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Irlene confirma.')
            print('"Isso. Frontend completo não é só beleza."')
            print('"É a experiência visível funcionando com clareza, reação e adaptação."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Irlene reancora com calma.')
            print('"Quase. Beleza visual ajuda, mas não basta."')
            print('"Uma interface também precisa ter estrutura, reação e adaptação."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Irlene aponta para a experiência do usuário.')
            print('"Boa tentativa. Backend e banco são importantes, mas não substituem a tela."')
            print('"O usuário precisa de uma interface para usar o sistema."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def cena_abertura_etapa_5():
    print()
    print("=" * 60)
    print("🎬 INICIAR MISSÃO: A INTERFACE VISUAL")
    print("=" * 60)
    print("Você retorna ao Centro de Operações da CampOne.")
    print()
    print("Eloisa já tinha mostrado a Grande Rede.")
    print("David abriu o Motor Oculto.")
    print("Letícia organizou a memória do sistema.")
    print("Renato mostrou como a tela conversa com o backend.")
    print()
    print("Agora falta olhar para a própria tela.")
    print()
    print("Irlene aparece na tela e olha diretamente para você.")
    print()
    print('"Olá. Eu sou Irlene."')
    print()
    print('"Minha área é Frontend."')
    print('"Eu cuido da parte do sistema que o usuário vê, toca e usa."')
    print()
    print('"Botões, textos, campos, imagens, organização visual e interação')
    print('não aparecem por acaso."')
    print()
    print('"Uma tela precisa existir, ser clara, reagir e funcionar bem')
    print('em diferentes tamanhos de tela."')
    print()
    print('"Frontend não é só deixar bonito."')
    print('"É transformar o sistema em uma experiência que uma pessoa consegue usar."')
    print()
    print("Nesta etapa, você vai entender:")
    print()
    print("- o que é frontend;")
    print("- como a estrutura da página nasce;")
    print("- como a aparência visual é organizada;")
    print("- como a tela reage ao usuário;")
    print("- como a página encontra partes específicas para mudar;")
    print("- por que a interface precisa se adaptar ao celular, tablet e computador;")
    print("- e como tudo isso forma a experiência visual do sistema.")
    print()
    print("Irlene aponta para uma tela da CampOne.")
    print()
    print('"Antes de aprender a construir telas na prática,')
    print('você precisa entender o papel de cada peça."')
    print()
    print('"Sem decorar código."')
    print('"Sem sintaxe disfarçada."')
    print('"Primeiro a ideia. Depois a ferramenta."')
    print("=" * 60)

    input("Pressione Enter para voltar...")


def reconhecimento_etapa_5():
    while True:
        print()
        print("=" * 60)
        print("💡 RECONHECIMENTO: A INTERFACE VISUAL")
        print("=" * 60)
        print("Irlene organiza os primeiros conceitos de Frontend.")
        print()
        print("1 - O que é Frontend")
        print("2 - HTML — estrutura da página")
        print("3 - CSS — aparência visual")
        print("4 - JavaScript — comportamento da tela")
        print("5 - DOM — mapa vivo da página")
        print("6 - Responsividade — tela que se adapta")
        print("7 - Frontend completo")
        print("0 - Voltar à etapa 05")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            topico_frontend_etapa_5()
        elif escolha == "2":
            topico_html_etapa_5()
        elif escolha == "3":
            topico_css_etapa_5()
        elif escolha == "4":
            topico_javascript_etapa_5()
        elif escolha == "5":
            topico_dom_etapa_5()
        elif escolha == "6":
            topico_responsividade_etapa_5()
        elif escolha == "7":
            topico_frontend_completo_etapa_5()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")


def campo_treinamento_etapa_5():
    print()
    print("=" * 60)
    print("🛠️ CAMPO DE TREINAMENTO: A TELA POR DENTRO")
    print("=" * 60)
    print("Agora vamos olhar uma tela da CampOne por dentro.")
    print()
    print("Cena:")
    print("O aplicativo mostra uma página simples de produtos.")
    print()
    print("Na tela existem:")
    print("- um título;")
    print("- uma imagem;")
    print("- uma lista de produtos;")
    print("- um botão de detalhes;")
    print("- um campo de busca.")
    print()
    print("-" * 60)
    print("1. HTML — O QUE EXISTE")
    print("-" * 60)
    print("Primeiro, a tela precisa dizer quais peças existem.")
    print()
    print("O HTML marca a estrutura:")
    print("existe um título, existe uma imagem, existe um botão, existe um campo.")
    print()
    print("Sem estrutura, a página nem sabe o que precisa mostrar.")
    print()
    print("-" * 60)
    print("2. CSS — COMO APARECE")
    print("-" * 60)
    print("Depois, essas peças precisam ficar organizadas e legíveis.")
    print()
    print("O CSS cuida da aparência:")
    print("cores, tamanhos, fontes, espaços e posição dos elementos.")
    print()
    print("Sem aparência bem cuidada, a informação até aparece,")
    print("mas pode ficar confusa ou difícil de usar.")
    print()
    print("-" * 60)
    print("3. JAVASCRIPT — COMO REAGE")
    print("-" * 60)
    print("Agora imagine que o usuário toca no botão de detalhes.")
    print()
    print("A tela precisa reagir.")
    print("Pode abrir uma informação, mostrar um aviso ou atualizar uma parte da página.")
    print()
    print("JavaScript é a parte que dá comportamento para a interface.")
    print()
    print("-" * 60)
    print("4. DOM — COMO ENCONTRA A PEÇA CERTA")
    print("-" * 60)
    print("Se existem muitos botões na tela,")
    print("o sistema precisa saber exatamente qual botão foi tocado.")
    print()
    print("O DOM funciona como um mapa vivo da página.")
    print("Ele ajuda a encontrar a peça certa para mudar só aquilo que precisa mudar.")
    print()
    print("-" * 60)
    print("5. RESPONSIVIDADE — COMO SE ADAPTA")
    print("-" * 60)
    print("A mesma tela pode abrir no computador, no tablet ou no celular.")
    print()
    print("A interface precisa se reorganizar para continuar fácil de usar.")
    print()
    print("Responsividade é isso:")
    print("a tela se adapta ao tamanho do dispositivo sem perder clareza.")
    print()
    print("-" * 60)
    print("RESUMO DA TELA POR DENTRO")
    print("-" * 60)
    print("HTML cria a estrutura.")
    print("CSS organiza a aparência.")
    print("JavaScript faz reagir.")
    print("DOM ajuda a encontrar a peça certa.")
    print("Responsividade adapta a tela ao dispositivo.")
    print()
    print("Ideia de sobrevivência:")
    print("frontend é a experiência visível do sistema funcionando para uma pessoa.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def laboratorio_falhas_etapa_5():
    print()
    print("=" * 60)
    print("🧪 LABORATÓRIO DE FALHAS: O PLANTÃO DA INTERFACE")
    print("=" * 60)
    print("Irlene aparece na tela e olha diretamente para você.")
    print()
    print("Agora vamos olhar alguns problemas comuns em uma interface visual.")
    print()
    print("A ideia não é sair corrigindo tudo no escuro.")
    print("A ideia é olhar o sintoma e suspeitar da peça certa.")
    print()
    print("-" * 60)
    print("CHAMADO 1 — TELA SEM ESTILO")
    print("-" * 60)
    print("O usuário abriu o app.")
    print("Tudo aparece na tela, mas está sem cor, sem espaçamento e tudo empilhado.")
    print()
    print("Suspeita principal:")
    print("CSS.")
    print()
    print("Por quê?")
    print("A estrutura existe, então o HTML provavelmente apareceu.")
    print("Mas a aparência visual não chegou direito.")
    print()
    print("-" * 60)
    print("CHAMADO 2 — TELA BONITA, MAS NADA REAGE")
    print("-" * 60)
    print("A tela aparece bonita.")
    print("Os botões estão no lugar.")
    print("Mas quando o usuário clica, nada acontece.")
    print()
    print("Suspeita principal:")
    print("JavaScript.")
    print()
    print("Por quê?")
    print("A aparência está presente, mas o comportamento não está funcionando.")
    print("A tela virou quase uma imagem parada.")
    print()
    print("-" * 60)
    print("CHAMADO 3 — TELA QUEBRADA NO CELULAR")
    print("-" * 60)
    print("No computador, a tela está boa.")
    print("No celular, tudo fica apertado, sobreposto ou difícil de tocar.")
    print()
    print("Suspeita principal:")
    print("Responsividade.")
    print()
    print("Por quê?")
    print("A interface não está se adaptando bem ao tamanho da tela.")
    print()
    print("-" * 60)
    print("CHAMADO 4 — ERRO 500")
    print("-" * 60)
    print("O app nem mostra a tela esperada.")
    print("Aparece uma mensagem de erro 500.")
    print()
    print("Suspeita principal:")
    print("backend ou servidor.")
    print()
    print("Por quê?")
    print("Erro 500 aponta para problema interno do servidor.")
    print("Nesse caso, a falha provavelmente não nasceu na interface visual.")
    print()
    print("-" * 60)
    print("IDEIA DE SOBREVIVÊNCIA")
    print("-" * 60)
    print("Problema visual nem sempre é do mesmo lugar.")
    print()
    print("Se tudo existe, mas está feio: olhe para o CSS.")
    print("Se está bonito, mas não reage: olhe para o JavaScript.")
    print("Se quebra no celular: olhe para a responsividade.")
    print("Se aparece erro 500: talvez o problema esteja fora do frontend.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def missao_producao_etapa_5():
    print()
    print("=" * 60)
    print("🏢 MISSÃO EM PRODUÇÃO: A INTERFACE NO MUNDO REAL")
    print("=" * 60)
    print("Irlene aparece na tela e olha diretamente para você.")
    print()
    print("Agora a interface visual sai do treinamento e entra no mundo real.")
    print()
    print("Imagine uma tela de catálogo da CampOne.")
    print()
    print("O usuário abre o sistema e vê:")
    print()
    print("- o nome da página;")
    print("- cards de produtos;")
    print("- imagens;")
    print("- preços;")
    print("- botão de detalhes;")
    print("- campo de busca;")
    print("- layout adaptado ao tamanho da tela.")
    print()
    print("-" * 60)
    print("O QUE O HTML FAZ")
    print("-" * 60)
    print("O HTML define as peças que existem nessa tela.")
    print()
    print("Ele diz que existe um título,")
    print("que existem imagens,")
    print("que existem botões,")
    print("que existe um campo de busca")
    print("e que existem áreas para mostrar produtos.")
    print()
    print("-" * 60)
    print("O QUE O CSS FAZ")
    print("-" * 60)
    print("O CSS organiza a aparência dessas peças.")
    print()
    print("Ele cuida das cores, fontes, tamanhos, espaços e alinhamento.")
    print()
    print("É o que faz a tela parecer uma interface da CampOne,")
    print("e não um monte de informação jogada na página.")
    print()
    print("-" * 60)
    print("O QUE O JAVASCRIPT FAZ")
    print("-" * 60)
    print("Quando o usuário clica em detalhes,")
    print("digita no campo de busca")
    print("ou interage com um botão,")
    print("a tela precisa reagir.")
    print()
    print("JavaScript é a parte que faz a interface responder às ações do usuário.")
    print()
    print("-" * 60)
    print("O QUE O DOM AJUDA A FAZER")
    print("-" * 60)
    print("Se existem vários produtos na tela,")
    print("o sistema precisa encontrar exatamente qual card, botão ou texto deve mudar.")
    print()
    print("O DOM ajuda a localizar a peça certa dentro da página.")
    print()
    print("-" * 60)
    print("O QUE A RESPONSIVIDADE RESOLVE")
    print("-" * 60)
    print("A mesma tela pode abrir no computador, no tablet ou no celular.")
    print()
    print("No computador há mais espaço.")
    print("No celular, os elementos precisam se reorganizar.")
    print()
    print("Responsividade mantém a tela usável em tamanhos diferentes.")
    print()
    print("-" * 60)
    print("IDEIA DE SOBREVIVÊNCIA")
    print("-" * 60)
    print("Em produção, Frontend não é só aparência.")
    print()
    print("É a soma de estrutura, visual, comportamento, localização das peças")
    print("e adaptação para diferentes telas.")
    print()
    print("Uma boa interface ajuda a pessoa a entender, clicar, ler e agir sem se perder.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def prova_dominio_etapa_5():
    while True:
        print()
        print("=" * 60)
        print("✅ PROVA DE DOMÍNIO: A INTERFACE VISUAL")
        print("=" * 60)
        print("Irlene aparece na tela e olha diretamente para você.")
        print()
        print('"Agora vamos juntar os sintomas de uma interface real."')
        print()
        print("Um usuário abre uma tela de produtos.")
        print("Tudo aparece, mas está sem estilo.")
        print("Depois, em outra tela, tudo está bonito, mas os botões não reagem.")
        print("Em um celular, a tela fica apertada e difícil de usar.")
        print()
        print("PERGUNTA:")
        print("Qual leitura mostra melhor o diagnóstico?")
        print()
        print("1 - Todos os problemas são do banco de dados, porque a tela sempre depende só dele.")
        print("2 - Todos os problemas são do backend, porque frontend não tem responsabilidade sobre a experiência visual.")
        print("3 - A tela sem estilo aponta para CSS; a tela que não reage aponta para JavaScript; a tela ruim no celular aponta para responsividade.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "3":
            print()
            print("Irlene confirma.")
            print('"Isso. Você leu os sintomas como dev:"')
            print('"aparência aponta para CSS,"')
            print('"reação aponta para JavaScript,"')
            print('"e tela ruim no celular aponta para responsividade."')
            print()
            print("A interface visual está dominada na teoria.")
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Irlene reancora com calma.")
            print('"Quase. O banco guarda informações, mas os sintomas citados são visuais e de interação."')
            print('"Eles apontam primeiro para a interface."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "2":
            print()
            print("Irlene aponta para a responsabilidade do frontend.")
            print('"Boa tentativa. Backend é importante, mas frontend tem responsabilidade pela experiência visível."')
            print('"Aparência, reação e adaptação são sinais da interface."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def registro_etapa_5():
    print()
    print("=" * 60)
    print("📝 REGISTRAR EXPERIÊNCIA — A INTERFACE VISUAL")
    print("=" * 60)
    print("Irlene aparece na tela e olha diretamente para você.")
    print()
    print('"Vamos registrar o que você enxergou por trás da tela."')
    print()
    print("Você reconheceu que:")
    print()
    print("- frontend é a parte visível do sistema;")
    print("- HTML define a estrutura do que existe na tela;")
    print("- CSS organiza a aparência visual;")
    print("- JavaScript faz a tela reagir;")
    print("- DOM ajuda a encontrar a peça certa da página;")
    print("- responsividade adapta a interface para diferentes tamanhos de tela;")
    print("- frontend completo não é só beleza;")
    print("- uma boa interface precisa ser clara, útil, reativa e adaptável.")
    print()
    print("Irlene confirma:")
    print()
    print('"Isso ainda não é programação prática."')
    print('"É visão de interface."')
    print()
    print('"Você agora entende a tela antes de aprender a construí-la com ferramentas profissionais."')
    print()
    print("Experiência registrada apenas na narrativa.")
    print("Salvamento real será criado em uma fase futura.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def relatorio_final_etapa_5():
    print()
    print("=" * 60)
    print("📋 RELATÓRIO FINAL — A INTERFACE VISUAL")
    print("=" * 60)
    print("Irlene aparece na tela e olha diretamente para você.")
    print()
    print('"Antes de seguir, revise a interface inteira."')
    print()
    print("Relatório da missão: Forjando a Interface Visual")
    print()
    print("Você agora sabe que:")
    print()
    print("- frontend é a experiência visível do sistema;")
    print("- a tela precisa existir antes de ficar bonita ou interativa;")
    print("- HTML organiza a estrutura da página;")
    print("- CSS cuida da aparência, organização visual e adaptação;")
    print("- JavaScript adiciona comportamento e reação;")
    print("- DOM funciona como um mapa vivo da página;")
    print("- responsividade mantém a tela usável em computador, tablet e celular;")
    print("- problemas visuais podem ter causas diferentes;")
    print("- uma boa interface ajuda a pessoa a entender, clicar, ler e agir sem se perder.")
    print()
    print("Conclusão:")
    print()
    print("Você começou a enxergar que uma tela não é só decoração.")
    print()
    print("Ela é uma parte essencial do sistema.")
    print("É onde o usuário encontra o produto, entende o caminho e toma ações.")
    print()
    print("A etapa ainda não marca conclusão permanente nesta versão.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def entrar_etapa_5():
    while True:
        print()
        print("=" * 60)
        print("05. FORJANDO A INTERFACE VISUAL")
        print("=" * 60)
        print("Tema real: Frontend")
        print("Tipo: Treinamento de Sobrevivência")
        print("Status: Estrutura inicial")
        print("Mentora prevista: Irlene")
        print()
        print("CENTRO DE OPERAÇÕES")
        print("-" * 60)
        print("1 - Iniciar Missão")
        print("2 - Reconhecimento")
        print("3 - Campo de Treinamento")
        print("4 - Laboratório de Falhas")
        print("5 - Missão em Produção")
        print("6 - Prova de Domínio")
        print("7 - Registrar Experiência")
        print("8 - Relatório Final")
        print("0 - Retornar ao Nível 1")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            cena_abertura_etapa_5()
        elif escolha == "2":
            reconhecimento_etapa_5()
        elif escolha == "3":
            campo_treinamento_etapa_5()
        elif escolha == "4":
            laboratorio_falhas_etapa_5()
        elif escolha == "5":
            missao_producao_etapa_5()
        elif escolha == "6":
            prova_dominio_etapa_5()
        elif escolha == "7":
            registro_etapa_5()
        elif escolha == "8":
            relatorio_final_etapa_5()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")
