"""Etapa 09 — Desenhando a Planta-Mestra."""

def cena_abertura_etapa_9():
    print()
    print("=" * 60)
    print("🎬 INICIAR MISSÃO: A PLANTA-MESTRA")
    print("=" * 60)
    print("Você chega a uma sala ampla da CampOne.")
    print()
    print("Na parede, existe uma folha grande em branco.")
    print("Ao redor dela, estão as peças que você já conheceu:")
    print()
    print("- a rede;")
    print("- o backend;")
    print("- o banco de dados;")
    print("- a ponte entre frontend e backend;")
    print("- a interface visual;")
    print("- a portaria digital;")
    print("- o caderno do time;")
    print("- e o sistema no ar.")
    print()
    print("Agora falta entender como tudo isso se organiza.")
    print()
    print("Adria aparece na tela e olha diretamente para você.")
    print()
    print("Olá. Eu sou Adria.")
    print()
    print("Minha área é Arquitetura.")
    print("Eu ajudo o time a enxergar a planta do sistema antes de construir ou mudar qualquer coisa.")
    print()
    print("Arquitetura não é enfeite.")
    print("É entender onde cada parte mora, pelo que ela é responsável e como conversa com as outras.")
    print()
    print("Nesta etapa, você vai entender:")
    print()
    print("- o que é arquitetura de software;")
    print("- por que cliente e servidor ficam separados;")
    print("- como as camadas do sistema se organizam;")
    print("- como frontend, backend, banco, API, segurança e deploy trabalham juntos;")
    print("- como um pedido atravessa a planta inteira;")
    print("- e por que uma boa planta ajuda o time a diagnosticar problemas.")
    print()
    print("Adria aponta para a folha em branco.")
    print()
    print("Sem decorar nomes.")
    print("Sem sintaxe disfarçada.")
    print("Primeiro você entende a planta.")
    print("Depois, no mundo prático, aprende a construir com organização.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def topico_arquitetura_etapa_9():
    while True:
        print()
        print("=" * 60)
        print('🏛️ TÓPICO 1: O QUE É ARQUITETURA')
        print("=" * 60)
        print('Arquitetura é a planta do sistema.')
        print()
        print('Ela mostra onde cada parte fica, qual responsabilidade cada uma tem')
        print('e como essas partes conversam entre si.')
        print()
        print('Adria olha diretamente para você.')
        print()
        print('Antes de construir rápido, o time precisa saber que casa está construindo.')
        print()
        print('Ideia de sobrevivência:')
        print('arquitetura é a organização das partes do sistema.')
        print()
        print("PERGUNTA:")
        print('O que melhor descreve arquitetura de software?')
        print()
        print('1 - Um conjunto de cores e botões bonitos na tela.')
        print('2 - A organização das partes do sistema, mostrando onde cada peça fica, sua responsabilidade e como conversa com as outras.')
        print('3 - Um lugar onde o banco de dados guarda senhas para sempre.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Adria confirma.')
            print('"Isso. Arquitetura é a planta do sistema."')
            print('"Ela ajuda o time a entender onde cada parte mora e como tudo conversa."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Adria reancora com calma.')
            print('"Quase. Cores e botões fazem parte da interface visual."')
            print('"Arquitetura olha para a organização do sistema inteiro."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Adria aponta para a planta completa.')
            print('"Boa tentativa. Banco de dados guarda informações, mas arquitetura não é só armazenamento."')
            print('"Ela mostra a planta completa das partes do sistema."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_cliente_servidor_etapa_9():
    while True:
        print()
        print("=" * 60)
        print('🧱 TÓPICO 2: CLIENTE E SERVIDOR')
        print("=" * 60)
        print('Todo sistema web tem dois lados importantes.')
        print()
        print('O cliente é o lado que a pessoa usa:')
        print('navegador, aplicativo, tela, botão, formulário.')
        print()
        print('O servidor é o lado que responde:')
        print('regras, processamento, dados, segurança e respostas.')
        print()
        print('Adria desenha uma linha separando os dois lados.')
        print()
        print('O cliente pede. O servidor responde.')
        print()
        print('Ideia de sobrevivência:')
        print('cliente e servidor são lados separados que conversam.')
        print()
        print("PERGUNTA:")
        print('Em uma arquitetura web, qual é a ideia principal entre cliente e servidor?')
        print()
        print('1 - O cliente pede, e o servidor recebe, trabalha e responde.')
        print('2 - O cliente guarda todos os dados sozinho, sem servidor.')
        print('3 - O servidor escolhe as cores da tela do usuário sem nenhuma comunicação.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            print()
            print('Adria confirma.')
            print('"Isso. Cliente e servidor são lados separados que conversam."')
            print('"O cliente pede; o servidor responde."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '2':
            print()
            print('Adria reancora com calma.')
            print('"Quase. O cliente usa a tela, mas não carrega o sistema inteiro sozinho."')
            print('"Quando precisa de dados ou regras, ele conversa com o servidor."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Adria separa visual de arquitetura.')
            print('"Boa tentativa, mas cor da tela é assunto de frontend."')
            print('"Servidor entra para responder pedidos e aplicar regras."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_camadas_etapa_9():
    while True:
        print()
        print("=" * 60)
        print('🏗️ TÓPICO 3: CAMADAS DO SISTEMA')
        print("=" * 60)
        print('Um sistema organizado não mistura tudo no mesmo lugar.')
        print()
        print('Cada camada tem uma responsabilidade.')
        print()
        print('A interface mostra e recebe ações.')
        print('O backend aplica regras.')
        print('O banco guarda informações.')
        print('A segurança controla acesso.')
        print('O deploy coloca o sistema no ar.')
        print()
        print('Adria aponta para a planta.')
        print()
        print('Quando cada camada sabe seu papel, o sistema fica mais fácil de entender e manter.')
        print()
        print('Ideia de sobrevivência:')
        print('camadas separam responsabilidades.')
        print()
        print("PERGUNTA:")
        print('Por que separar o sistema em camadas ajuda a manter a organização?')
        print()
        print('1 - Porque todas as partes passam a fazer exatamente a mesma coisa.')
        print('2 - Porque a separação apaga o histórico do projeto.')
        print('3 - Porque cada parte tem uma responsabilidade clara, como interface, regras, dados, segurança e publicação.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '3':
            print()
            print('Adria confirma.')
            print('"Isso. Camadas separam responsabilidades."')
            print('"Quando cada parte sabe seu papel, o sistema fica mais fácil de entender e manter."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Adria reancora com calma.')
            print('"Quase. Camadas não existem para todo mundo fazer a mesma coisa."')
            print('"Elas existem para separar responsabilidades."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '2':
            print()
            print('Adria aponta para outro tema.')
            print('"Boa tentativa, mas histórico do projeto é tema de Git."')
            print('"Camadas ajudam a organizar as funções internas do sistema."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_api_planta_etapa_9():
    while True:
        print()
        print("=" * 60)
        print('🌉 TÓPICO 4: API — A JANELA ENTRE AS PARTES')
        print("=" * 60)
        print('As partes do sistema precisam conversar sem virar bagunça.')
        print()
        print('A API organiza a conversa entre a tela e o backend.')
        print()
        print('Ela funciona como uma janela de pedidos e respostas.')
        print()
        print('Adria desenha uma passagem entre a interface e o backend.')
        print()
        print('A tela não entra na cozinha do sistema.')
        print('Ela pede pela janela certa.')
        print()
        print('Ideia de sobrevivência:')
        print('API organiza a comunicação entre partes do sistema.')
        print()
        print("PERGUNTA:")
        print('Na planta do sistema, qual é o papel da API?')
        print()
        print('1 - Guardar todos os dados no lugar do banco.')
        print('2 - Organizar a comunicação entre partes, como a tela e o backend.')
        print('3 - Trocar automaticamente o layout da página no celular.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Adria confirma.')
            print('"Isso. API organiza a comunicação."')
            print('"Ela permite que a tela peça e o backend responda por caminhos combinados."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Adria reancora com calma.')
            print('"Quase. Guardar dados é papel do banco de dados."')
            print('"A API organiza a conversa entre partes do sistema."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Adria aponta para a janela correta.')
            print('"Boa tentativa, mas adaptação visual é tema de responsividade."')
            print('"A API é a janela de pedidos e respostas entre partes."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_fluxo_pedido_etapa_9():
    while True:
        print()
        print("=" * 60)
        print('🔁 TÓPICO 5: O CAMINHO COMPLETO DO PEDIDO')
        print("=" * 60)
        print('Agora a planta ganha movimento.')
        print()
        print('Um usuário toca na tela.')
        print('A interface cria um pedido.')
        print('O pedido passa pela internet.')
        print('A segurança pode conferir quem está pedindo.')
        print('O backend aplica regras.')
        print('O banco pode ser consultado.')
        print('A resposta volta.')
        print('A tela mostra o resultado.')
        print()
        print('Adria acompanha o caminho com o dedo na planta.')
        print()
        print('Ideia de sobrevivência:')
        print('arquitetura ajuda a seguir o pedido de ponta a ponta.')
        print()
        print("PERGUNTA:")
        print('Qual caminho representa melhor um pedido atravessando a planta do sistema?')
        print()
        print('1 - Usuário toca na tela, frontend monta pedido, segurança pode conferir, backend aplica regras, banco pode participar, resposta volta para a tela.')
        print('2 - O banco aparece direto para o usuário e decide sozinho o que mostrar.')
        print('3 - O frontend cria todos os dados sozinho sem pedir nada para outras partes.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            print()
            print('Adria confirma.')
            print('"Isso. Você seguiu o pedido pela planta."')
            print('"A arquitetura ajuda a enxergar o caminho de ponta a ponta."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '2':
            print()
            print('Adria reancora com calma.')
            print('"Quase. O banco guarda dados, mas normalmente não aparece direto para o usuário."')
            print('"O pedido passa por outras partes antes da resposta voltar."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Adria aponta para o caminho completo.')
            print('"Boa tentativa, mas o frontend não faz tudo sozinho."')
            print('"Ele pede, recebe resposta e mostra o resultado."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_diagnostico_etapa_9():
    while True:
        print()
        print("=" * 60)
        print('🧭 TÓPICO 6: DIAGNÓSTICO PELA PLANTA')
        print("=" * 60)
        print('Quando algo quebra, a planta ajuda o time a não chutar no escuro.')
        print()
        print('Se a tela não reage, olhe para a interface.')
        print('Se o pedido falha, olhe a comunicação.')
        print('Se a regra dá errado, olhe o backend.')
        print('Se a informação some, olhe o banco.')
        print('Se o acesso é recusado, olhe a segurança.')
        print('Se o sistema não abre para ninguém, olhe deploy, servidor ou domínio.')
        print()
        print('Adria confirma.')
        print()
        print('A planta não resolve tudo sozinha, mas mostra onde procurar.')
        print()
        print('Ideia de sobrevivência:')
        print('arquitetura transforma problema confuso em suspeitas organizadas.')
        print()
        print("PERGUNTA:")
        print('Quando algo quebra, por que a planta do sistema ajuda no diagnóstico?')
        print()
        print('1 - Porque ela resolve todos os erros automaticamente sem análise.')
        print('2 - Porque ela troca a senha do usuário sempre que aparece um bug.')
        print('3 - Porque ela mostra onde procurar: tela, comunicação, backend, banco, segurança, deploy ou outro ponto da arquitetura.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '3':
            print()
            print('Adria confirma.')
            print('"Isso. Arquitetura transforma confusão em suspeitas organizadas."')
            print('"Ela mostra por onde começar a investigação."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Adria reancora com calma.')
            print('"Quase. A planta não resolve tudo sozinha."')
            print('"Ela ajuda o time a saber onde investigar."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '2':
            print()
            print('Adria aponta para outra área.')
            print('"Boa tentativa, mas senha é assunto de segurança."')
            print('"Diagnóstico pela planta é descobrir onde o problema pode estar."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_planta_mestra_etapa_9():
    while True:
        print()
        print("=" * 60)
        print('🗺️ TÓPICO 7: A PLANTA-MESTRA')
        print("=" * 60)
        print('A planta-mestra junta tudo que você viu na Academy.')
        print()
        print('Rede para o caminho.')
        print('Backend para regras.')
        print('Banco para memória.')
        print('API para comunicação.')
        print('Frontend para experiência visual.')
        print('Segurança para entrada e permissão.')
        print('Git e GitHub para histórico do time.')
        print('Deploy para colocar no ar.')
        print()
        print('Adria olha diretamente para você.')
        print()
        print('Você não aprendeu peças soltas.')
        print('Você percorreu a planta inteira do sistema.')
        print()
        print('Ideia de sobrevivência:')
        print('arquitetura é enxergar o sistema inteiro sem se perder nas partes.')
        print()
        print("PERGUNTA:")
        print('O que a planta-mestra representa depois de todas as etapas da Academy?')
        print()
        print('1 - Apenas uma lista de comandos para decorar antes da prática.')
        print('2 - A visão do sistema inteiro, juntando rede, backend, banco, API, frontend, segurança, Git, deploy e responsabilidades.')
        print('3 - Um desenho sem utilidade que não ajuda o time a trabalhar.')
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == '2':
            print()
            print('Adria confirma.')
            print('"Isso. A planta-mestra junta tudo."')
            print('"Você não aprendeu peças soltas; você enxergou o sistema inteiro."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == '1':
            print()
            print('Adria reancora com calma.')
            print('"Quase. A Academy não está criando lista de comandos."')
            print('"Ela está formando visão de sistema antes da prática."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == '3':
            print()
            print('Adria aponta para a utilidade da planta.')
            print('"Boa tentativa, mas a planta tem utilidade real."')
            print('"Ela ajuda o time a conversar, construir, manter e diagnosticar."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def reconhecimento_etapa_9():
    while True:
        print()
        print("=" * 60)
        print("💡 RECONHECIMENTO: A PLANTA DO SISTEMA")
        print("=" * 60)
        print("Adria organiza os primeiros conceitos de Arquitetura.")
        print()
        print("1 - O que é Arquitetura")
        print("2 - Cliente e Servidor")
        print("3 - Camadas do Sistema")
        print("4 - API — a janela entre as partes")
        print("5 - O caminho completo do pedido")
        print("6 - Diagnóstico pela planta")
        print("7 - A Planta-Mestra")
        print("0 - Voltar à etapa 09")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            topico_arquitetura_etapa_9()
        elif escolha == "2":
            topico_cliente_servidor_etapa_9()
        elif escolha == "3":
            topico_camadas_etapa_9()
        elif escolha == "4":
            topico_api_planta_etapa_9()
        elif escolha == "5":
            topico_fluxo_pedido_etapa_9()
        elif escolha == "6":
            topico_diagnostico_etapa_9()
        elif escolha == "7":
            topico_planta_mestra_etapa_9()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")


def campo_treinamento_etapa_9():
    print()
    print("=" * 60)
    print("🛠️ CAMPO DE TREINAMENTO: SEGUINDO UM PEDIDO PELA PLANTA")
    print("=" * 60)
    print("Adria aparece na tela e olha diretamente para você.")
    print()
    print("Vamos seguir um pedido atravessando o sistema inteiro.")
    print()
    print("Cena:")
    print("Uma pessoa tenta reservar um horário pelo app da CampOne.")
    print()
    print("1. A pessoa toca na tela.")
    print("2. O frontend monta o pedido.")
    print("3. A internet leva o pedido até o servidor.")
    print("4. A segurança confere se a pessoa pode fazer aquilo.")
    print("5. O backend aplica as regras da reserva.")
    print("6. O banco verifica e guarda as informações.")
    print("7. O backend monta a resposta.")
    print("8. A tela mostra o resultado.")
    print()
    print("Ideia de sobrevivência:")
    print("arquitetura é saber por onde o pedido passa e quem faz cada parte.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def laboratorio_falhas_etapa_9():
    print()
    print("=" * 60)
    print("🧪 LABORATÓRIO DE FALHAS: ONDE O PEDIDO PAROU?")
    print("=" * 60)
    print("Adria aparece na tela e olha diretamente para você.")
    print()
    print("Agora vamos diagnosticar problemas usando a planta.")
    print()
    print("1. A tela está quebrada ou não reage.")
    print("Suspeita: frontend.")
    print()
    print("2. A tela pede, mas a resposta volta errada.")
    print("Suspeita: API, rota ou backend.")
    print()
    print("3. O sistema esquece dados ou mostra informação incorreta.")
    print("Suspeita: banco de dados ou regra de negócio.")
    print()
    print("4. A pessoa não consegue acessar uma área.")
    print("Suspeita: segurança, autenticação ou autorização.")
    print()
    print("5. O site nem abre pelo endereço.")
    print("Suspeita: deploy, servidor, domínio ou DNS.")
    print()
    print("Ideia de sobrevivência:")
    print("a planta ajuda a transformar erro confuso em investigação organizada.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def missao_producao_etapa_9():
    print()
    print("=" * 60)
    print("🏢 MISSÃO EM PRODUÇÃO: LENDO A PLANTA DA CAMPONE")
    print("=" * 60)
    print("Adria aparece na tela e olha diretamente para você.")
    print()
    print("A CampOne precisa evoluir o sistema sem se perder.")
    print()
    print("Antes de mexer em qualquer coisa, o time consulta a planta:")
    print()
    print("- o que aparece para o usuário?")
    print("- onde ficam as regras?")
    print("- onde os dados são guardados?")
    print("- por onde a tela conversa com o backend?")
    print("- quem pode acessar?")
    print("- como o sistema chega aos usuários?")
    print("- como o time registra mudanças?")
    print()
    print("A planta não é burocracia.")
    print("Ela evita que o time construa rápido a coisa errada.")
    print()
    print("Ideia de sobrevivência:")
    print("arquitetura ajuda a construir, conversar, manter e diagnosticar.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def prova_dominio_etapa_9():
    while True:
        print()
        print("=" * 60)
        print("✅ PROVA DE DOMÍNIO: A PLANTA-MESTRA")
        print("=" * 60)
        print("Adria aparece na tela e olha diretamente para você.")
        print()
        print("Um usuário tenta reservar um horário no app.")
        print("A tela monta um pedido,")
        print("a segurança confere o acesso,")
        print("o backend aplica regras,")
        print("o banco guarda a reserva,")
        print("a resposta volta")
        print("e a tela mostra a confirmação.")
        print()
        print("PERGUNTA:")
        print("Qual leitura mostra melhor essa arquitetura?")
        print()
        print("1 - A tela fez tudo sozinha e o resto do sistema não participou.")
        print("2 - O banco apareceu direto para o usuário e escolheu sozinho o resultado.")
        print("3 - Várias partes trabalharam juntas, cada uma com sua responsabilidade, formando o caminho completo do pedido.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "3":
            print()
            print("Adria confirma.")
            print('"Isso. Essa é a visão de arquitetura."')
            print('"Cada parte tem responsabilidade, e juntas entregam a experiência ao usuário."')
            print()
            print("A planta-mestra da Academy está dominada na teoria.")
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Adria reancora com calma.")
            print('"Quase. A tela é importante, mas não faz tudo sozinha."')
            print('"Ela participa do caminho junto com outras partes."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "2":
            print()
            print("Adria aponta para as camadas.")
            print('"Boa tentativa, mas o banco não aparece direto para o usuário."')
            print('"Ele participa por trás, junto com backend e outras camadas."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def registro_etapa_9():
    print()
    print("=" * 60)
    print("📝 REGISTRAR EXPERIÊNCIA — A PLANTA-MESTRA")
    print("=" * 60)
    print("Adria aparece na tela e olha diretamente para você.")
    print()
    print("Vamos registrar o que você entendeu sobre Arquitetura.")
    print()
    print("Você reconheceu que:")
    print()
    print("- arquitetura é a planta do sistema;")
    print("- cliente e servidor são lados separados que conversam;")
    print("- camadas separam responsabilidades;")
    print("- API organiza a comunicação entre partes;")
    print("- um pedido atravessa várias camadas;")
    print("- diagnóstico melhora quando o time sabe onde procurar;")
    print("- a planta-mestra junta tudo que a Academy ensinou.")
    print()
    print("Adria confirma:")
    print()
    print("Isso ainda não é programação prática.")
    print("É visão de sistema.")
    print()
    print("Experiência registrada apenas na narrativa.")
    print("Salvamento real será criado em uma fase futura.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def relatorio_final_etapa_9():
    print()
    print("=" * 60)
    print("📋 RELATÓRIO FINAL — A PLANTA-MESTRA")
    print("=" * 60)
    print("Adria aparece na tela e olha diretamente para você.")
    print()
    print("Relatório da missão: Desenhando a Planta-Mestra")
    print()
    print("Você agora sabe que:")
    print()
    print("- a internet é o caminho;")
    print("- o backend aplica regras;")
    print("- o banco guarda memória;")
    print("- a API organiza a conversa;")
    print("- o frontend entrega a experiência visual;")
    print("- a segurança protege entrada e permissões;")
    print("- Git e GitHub guardam o histórico do time;")
    print("- deploy coloca o sistema no ar;")
    print("- arquitetura junta tudo em uma planta compreensível.")
    print()
    print("Conclusão:")
    print()
    print("Você concluiu a Academy teórica.")
    print()
    print("Agora você não enxerga mais peças soltas.")
    print("Você enxerga o sistema como uma casa inteira.")
    print()
    print("A Academy está pronta para ser fechada antes da futura consolidação da Engine.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def entrar_etapa_9():
    while True:
        print()
        print("=" * 60)
        print("09. DESENHANDO A PLANTA-MESTRA")
        print("=" * 60)
        print("Tema real: Arquitetura")
        print("Tipo: Treinamento de Sobrevivência")
        print("Status: Estrutura inicial")
        print("Mentora prevista: Adria")
        print()
        print("CENTRO DE OPERAÇÕES")
        print("-" * 60)
        print("1 - Iniciar Missão")
        print("2 - Reconhecimento")
        print("3 - Campo de Treinamento")
        print("4 - Laboratório de Falhas")
        print("5 - Missão em Produção")
        print("6 - Prova de Domínio")
        print("7 - Registrar Experiência")
        print("8 - Relatório Final")
        print("0 - Retornar ao Nível 1")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            cena_abertura_etapa_9()
        elif escolha == "2":
            reconhecimento_etapa_9()
        elif escolha == "3":
            campo_treinamento_etapa_9()
        elif escolha == "4":
            laboratorio_falhas_etapa_9()
        elif escolha == "5":
            missao_producao_etapa_9()
        elif escolha == "6":
            prova_dominio_etapa_9()
        elif escolha == "7":
            registro_etapa_9()
        elif escolha == "8":
            relatorio_final_etapa_9()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")
