"""Etapa 04 — Construindo a Ponte dos Mundos."""

def topico_comunicacao_frontend_backend_etapa_4():
    while True:
        print()
        print("=" * 60)
        print("🌉 TÓPICO 1: COMO FRONTEND E BACKEND SE COMUNICAM")
        print("=" * 60)
        print("A tela não faz tudo sozinha.")
        print()
        print("Quando o usuário clica em um botão, a tela faz um pedido.")
        print("Esse pedido viaja até o backend.")
        print("O backend recebe, trabalha e devolve uma resposta.")
        print()
        print("Ideia de sobrevivência:")
        print("frontend pede, backend responde, frontend mostra.")
        print()
        print("PERGUNTA:")
        print("Quando o usuário clica em uma tela para ver produtos,")
        print("o que melhor descreve a conversa entre frontend e backend?")
        print()
        print("1 - A tela faz um pedido, o backend recebe, trabalha e devolve uma resposta para a tela mostrar.")
        print("2 - A tela resolve tudo sozinha, sem precisar conversar com o backend.")
        print("3 - O banco de dados aparece direto na tela e escolhe o que o usuário vai ver.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            print()
            print("Renato confirma.")
            print('"Isso. A tela pede, o backend entende, trabalha e responde."')
            print('"Essa é a ponte básica entre os dois mundos."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == "2":
            print()
            print("Renato reancora com calma.")
            print('"Quase. A tela é importante, mas ela não carrega o sistema inteiro sozinha."')
            print('"Ela mostra, pergunta e recebe respostas."')
            print('"Quem trabalha por trás é o backend."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "3":
            print()
            print("Renato aponta para a ponte entre as partes.")
            print('"Boa tentativa. O banco guarda informações, mas ele não aparece direto para o usuário."')
            print('"Normalmente, quem conversa com o banco é o backend."')
            print('"A tela recebe uma resposta já preparada."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_api_rest_pratica_etapa_4():
    while True:
        print()
        print("=" * 60)
        print("🧭 TÓPICO 2: API REST NA PRÁTICA")
        print("=" * 60)
        print("Pedido sem caminho combinado vira bagunça.")
        print()
        print("A API REST é um jeito organizado de combinar os pedidos")
        print("entre a tela e o backend.")
        print()
        print("Pensa como um cardápio de portas:")
        print("uma porta para produtos, outra para clientes, outra para pedidos.")
        print()
        print("Ideia de sobrevivência:")
        print("API REST organiza como a tela pede e como o backend entende.")
        print()
        print("PERGUNTA:")
        print("Por que uma API ajuda na conversa entre a tela e o backend?")
        print()
        print("1 - Porque ela troca as cores, fontes e botões que aparecem na tela.")
        print("2 - Porque ela organiza os caminhos dos pedidos, ajudando a tela e o backend a se entenderem.")
        print("3 - Porque ela guarda todos os dados sozinha, sem precisar de backend ou banco.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "2":
            print()
            print("Renato confirma.")
            print('"Isso. A API funciona como um conjunto de caminhos combinados."')
            print('"A tela sabe por onde pedir, e o backend sabe como responder."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Renato reancora com calma.")
            print('"Quase. Cores, fontes e botões fazem parte da interface visual."')
            print('"A API não cuida da aparência da tela."')
            print('"Ela ajuda a organizar a conversa entre a tela e o backend."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "3":
            print()
            print("Renato aponta para os caminhos da ponte.")
            print('"Boa tentativa. Guardar dados é papel do banco."')
            print('"A API não substitui o backend nem o banco."')
            print('"Ela funciona como um caminho organizado para os pedidos chegarem ao lugar certo."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_get_etapa_4():
    while True:
        print()
        print("=" * 60)
        print("🔎 TÓPICO 3: GET — BUSCAR DADOS")
        print("=" * 60)
        print("Às vezes a tela só quer olhar uma informação.")
        print()
        print("GET é o pedido usado para buscar dados sem mudar nada.")
        print()
        print("Exemplo:")
        print("abrir uma lista de produtos, ver um perfil ou carregar um catálogo.")
        print()
        print("Ideia de sobrevivência:")
        print("GET é olhar, não mexer.")
        print()
        print("PERGUNTA:")
        print("Quando a tela precisa apenas mostrar uma lista de produtos,")
        print("sem criar nem alterar nada, que tipo de pedido faz mais sentido?")
        print()
        print("1 - POST, porque qualquer clique sempre cria alguma coisa nova no sistema.")
        print("2 - DELETE, porque buscar uma lista significa apagar os dados antigos primeiro.")
        print("3 - GET, porque a tela só quer buscar informações sem mexer nos dados.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "3":
            print()
            print("Renato confirma.")
            print('"Isso. GET é o pedido de olhar."')
            print('"A tela pede informação, o backend busca e devolve sem alterar os dados."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Renato reancora com calma.")
            print('"Quase. POST entra quando a tela está enviando algo novo para o sistema criar ou processar."')
            print('"Se a tela só quer ver uma lista, ela está buscando, não criando."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "2":
            print()
            print("Renato aponta para a intenção do pedido.")
            print('"Boa tentativa, mas DELETE é usado quando a intenção é apagar algo."')
            print('"Buscar uma lista não apaga nada."')
            print('"É só olhar o que já existe."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_post_etapa_4():
    while True:
        print()
        print("=" * 60)
        print("📨 TÓPICO 4: POST — ENVIAR ALGO NOVO")
        print("=" * 60)
        print("Às vezes a tela precisa mandar uma informação nova.")
        print()
        print("POST é o pedido usado para criar ou enviar dados novos.")
        print()
        print("Exemplo:")
        print("criar uma conta, fazer uma compra ou enviar uma mensagem.")
        print()
        print("Ideia de sobrevivência:")
        print("POST leva algo novo para o backend guardar ou processar.")
        print()
        print("PERGUNTA:")
        print("Quando a tela envia nome e preço para cadastrar um produto novo,")
        print("que tipo de pedido faz mais sentido?")
        print()
        print("1 - GET, porque cadastrar produto é só olhar a lista que já existe.")
        print("2 - POST, porque a tela está enviando uma informação nova para o sistema criar ou processar.")
        print("3 - DELETE, porque todo cadastro novo apaga automaticamente os produtos antigos.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "2":
            print()
            print("Renato confirma.")
            print('"Isso. POST é o pedido de enviar algo novo."')
            print('"A tela manda os dados, o backend recebe e o sistema pode criar um novo registro."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Renato reancora com calma.")
            print('"Quase. GET é usado quando a tela só quer buscar ou olhar informações."')
            print('"Aqui a tela está enviando dados novos."')
            print('"Quando algo novo precisa nascer no sistema, a ideia é POST."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "3":
            print()
            print("Renato aponta para a intenção do pedido.")
            print('"Boa tentativa, mas DELETE é usado quando a intenção é apagar."')
            print('"Cadastrar um produto novo não apaga os antigos."')
            print('"A tela está mandando algo novo para ser guardado."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_put_etapa_4():
    while True:
        print()
        print("=" * 60)
        print("✏️ TÓPICO 5: PUT — ATUALIZAR DADOS")
        print("=" * 60)
        print("O que já existe pode precisar ser corrigido.")
        print()
        print("PUT é o pedido usado para atualizar uma informação existente.")
        print()
        print("Exemplo:")
        print("alterar endereço, editar perfil ou mudar o status de um pedido.")
        print()
        print("Ideia de sobrevivência:")
        print("PUT mexe em algo que já existe.")
        print()
        print("PERGUNTA:")
        print("Quando uma pessoa altera o preço de um produto que já existe,")
        print("qual ideia combina melhor com esse pedido?")
        print()
        print("1 - GET, porque mudar preço é apenas olhar o produto sem mexer nele.")
        print("2 - POST, porque qualquer mudança em algo existente sempre cria um produto duplicado.")
        print("3 - PUT, porque o sistema está atualizando uma informação que já existia.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "3":
            print()
            print("Renato confirma.")
            print('"Isso. PUT entra quando algo existente precisa ser atualizado."')
            print('"O produto já estava no sistema; agora uma informação dele mudou."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Renato reancora com calma.")
            print('"Quase. GET é o pedido de olhar."')
            print('"Se o preço mudou, o sistema não está só olhando."')
            print('"Ele está alterando uma informação existente."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "2":
            print()
            print("Renato aponta para a diferença entre criar e atualizar.")
            print('"Boa tentativa. POST é muito usado quando algo novo precisa ser criado."')
            print('"Mas aqui o produto já existe."')
            print('"A ideia principal é atualizar o que já estava lá."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_delete_etapa_4():
    while True:
        print()
        print("=" * 60)
        print("🗑️ TÓPICO 6: DELETE — APAGAR DADOS")
        print("=" * 60)
        print("Às vezes uma informação precisa sair do sistema.")
        print()
        print("DELETE é o pedido usado para apagar um dado.")
        print()
        print("Exemplo:")
        print("remover um item, excluir uma foto ou cancelar um registro.")
        print()
        print("Ideia de sobrevivência:")
        print("DELETE apaga. Por isso exige cuidado.")
        print()
        print("PERGUNTA:")
        print("Quando o sistema precisa remover um produto cadastrado,")
        print("qual tipo de pedido representa melhor essa intenção?")
        print()
        print("1 - DELETE, porque a intenção é apagar uma informação do sistema.")
        print("2 - GET, porque apagar é só pedir para ver a lista de produtos.")
        print("3 - POST, porque apagar sempre significa criar um produto novo no lugar.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            print()
            print("Renato confirma.")
            print('"Isso. DELETE é o pedido de remoção."')
            print('"Ele precisa de cuidado porque mexe no que já existe no sistema."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == "2":
            print()
            print("Renato reancora com calma.")
            print('"Quase. GET é usado para buscar informações sem mexer nelas."')
            print('"Se a intenção é remover um produto, o sistema está fazendo uma mudança."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "3":
            print()
            print("Renato aponta para a intenção do pedido.")
            print('"Boa tentativa, mas POST está ligado a enviar algo novo."')
            print('"Apagar não cria um produto novo."')
            print('"Apagar remove algo que já existia."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_status_code_etapa_4():
    while True:
        print()
        print("=" * 60)
        print("🏷️ TÓPICO 7: CÓDIGOS DE RESULTADO")
        print("=" * 60)
        print("Toda resposta do backend vem com uma etiqueta.")
        print()
        print("Essa etiqueta diz se deu certo ou se algo falhou.")
        print()
        print("Exemplos importantes:")
        print("200 — deu certo")
        print("400 — o pedido veio incompleto ou estranho")
        print("401 — falta provar quem é")
        print("404 — não encontrou o que foi pedido")
        print("500 — quebrou algo dentro do servidor")
        print()
        print("Ideia de sobrevivência:")
        print("o código ajuda a descobrir onde procurar o problema.")
        print()
        print("PERGUNTA:")
        print("Se a tela pediu um produto e o backend respondeu 404,")
        print("o que isso indica?")
        print()
        print("1 - Deu tudo certo e a tela recebeu os dados normalmente.")
        print("2 - O pedido chegou, mas o sistema não encontrou o que foi pedido.")
        print("3 - A tela mudou de cor porque o frontend escolheu outro visual.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "2":
            print()
            print("Renato confirma.")
            print('"Isso. 404 não quer dizer que a tela escolheu errado uma cor."')
            print('"Quer dizer que o pedido chegou, mas aquilo que foi pedido não foi encontrado."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Renato reancora com calma.")
            print('"Quase. Quando dá tudo certo, o código mais comum é 200."')
            print('"O 404 aponta que o sistema procurou, mas não encontrou o recurso pedido."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "3":
            print()
            print("Renato aponta para a etiqueta da resposta.")
            print('"Boa tentativa, mas código de resultado não fala de cor ou aparência da tela."')
            print('"Ele ajuda a entender o que aconteceu com o pedido."')
            print('"404 indica que algo pedido não foi encontrado."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def topico_fluxo_completo_etapa_4():
    while True:
        print()
        print("=" * 60)
        print("🔁 TÓPICO 8: FLUXO COMPLETO")
        print("=" * 60)
        print("Agora juntamos tudo em uma viagem só.")
        print()
        print("Usuário clica.")
        print("A tela manda um pedido.")
        print("O pedido viaja pela internet.")
        print("O servidor recebe.")
        print("O backend trabalha.")
        print("O banco pode ser consultado.")
        print("A resposta volta.")
        print("A tela mostra o resultado.")
        print()
        print("Ideia de sobrevivência:")
        print("todo app moderno vive esse caminho de ida e volta.")
        print()
        print("PERGUNTA:")
        print("Qual caminho representa melhor a viagem completa")
        print("de um clique até a tela mostrar uma resposta?")
        print()
        print("1 - O usuário clica e o banco aparece direto na tela, sem backend e sem resposta.")
        print("2 - O usuário clica e o frontend cria todos os dados sozinho, sem conversar com outras partes.")
        print("3 - O usuário clica, a tela faz pedido, o backend trabalha, o banco pode ser consultado, a resposta volta e a tela mostra o resultado.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "3":
            print()
            print("Renato confirma.")
            print('"Isso. Esse é o mapa da ponte inteira."')
            print('"A tela pede, o backend trabalha, o banco pode participar, a resposta volta e a tela mostra."')
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Renato reancora com calma.")
            print('"Quase. O banco guarda informações, mas normalmente não aparece direto para o usuário."')
            print('"Entre a tela e o banco existe o backend organizando a conversa."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "2":
            print()
            print("Renato aponta para a ponte.")
            print('"Boa tentativa. O frontend mostra e recebe ações do usuário, mas não faz tudo sozinho."')
            print('"Quando precisa de dados ou regras, ele conversa com o backend."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def cena_abertura_etapa_4():
    print()
    print("=" * 60)
    print("🎬 INICIAR MISSÃO: A PONTE ENTRE OS MUNDOS")
    print("=" * 60)
    print("Você chega ao Centro de Operações da CampOne.")
    print()
    print("Eloisa já tinha mostrado o caminho da Grande Rede.")
    print("David abriu o Motor Oculto.")
    print("Letícia organizou a memória do sistema.")
    print()
    print("Mas uma pergunta ainda fica no ar:")
    print()
    print("como a tela conversa com tudo isso?")
    print()
    print("Renato aparece na tela e olha diretamente para você.")
    print()
    print('"Prazer, eu sou Renato."')
    print()
    print('"Minha área é integração:')
    print('eu cuido da ponte entre o que o usuário vê')
    print('e o que o sistema faz por trás."')
    print()
    print('"Quando alguém clica em uma tela,')
    print('esse clique precisa virar um pedido."')
    print()
    print('"Esse pedido precisa chegar ao backend."')
    print()
    print('"O backend precisa entender,')
    print('buscar ou guardar informação,')
    print('e devolver uma resposta que a tela consiga mostrar."')
    print()
    print('"É essa ponte que você vai aprender agora."')
    print()
    print("Nesta etapa, você vai entender:")
    print()
    print("- como frontend e backend se comunicam;")
    print("- por que uma API organiza essa conversa;")
    print("- quando o sistema está só buscando informações;")
    print("- quando está enviando algo novo;")
    print("- quando está atualizando ou apagando;")
    print("- como os códigos de resposta ajudam a diagnosticar falhas;")
    print("- e como tudo isso forma uma viagem completa.")
    print()
    print("Renato aponta para o mapa da CampOne.")
    print()
    print('"Você já viu a rede, o motor e a memória."')
    print()
    print('"Agora vai atravessar a ponte."')
    print()
    print('"Sem decorar código.')
    print('Sem sintaxe disfarçada."')
    print()
    print('"Primeiro você entende a viagem.')
    print('Depois, no mundo prático, aprende a operar as ferramentas."')
    print("=" * 60)

    input("Pressione Enter para voltar...")


def reconhecimento_etapa_4():
    while True:
        print()
        print("=" * 60)
        print("💡 RECONHECIMENTO: A PONTE ENTRE OS MUNDOS")
        print("=" * 60)
        print("Aqui você começa a organizar como a tela conversa com o backend.")
        print()
        print("1 - Como frontend e backend se comunicam")
        print("2 - API REST na prática")
        print("3 - GET — buscar dados")
        print("4 - POST — enviar algo novo")
        print("5 - PUT — atualizar dados")
        print("6 - DELETE — apagar dados")
        print("7 - Códigos de resultado")
        print("8 - Fluxo completo")
        print("0 - Voltar à etapa 04")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            topico_comunicacao_frontend_backend_etapa_4()
        elif escolha == "2":
            topico_api_rest_pratica_etapa_4()
        elif escolha == "3":
            topico_get_etapa_4()
        elif escolha == "4":
            topico_post_etapa_4()
        elif escolha == "5":
            topico_put_etapa_4()
        elif escolha == "6":
            topico_delete_etapa_4()
        elif escolha == "7":
            topico_status_code_etapa_4()
        elif escolha == "8":
            topico_fluxo_completo_etapa_4()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")


def campo_treinamento_etapa_4():
    print()
    print("=" * 60)
    print("🛠️ CAMPO DE TREINAMENTO: A VIAGEM DO PEDIDO")
    print("=" * 60)
    print("Agora vamos acompanhar um clique por dentro do sistema.")
    print()
    print("Cena:")
    print("O usuário abre o app da CampOne e clica em:")
    print('"Ver produtos"')
    print()
    print("1. A tela entende que precisa buscar informações.")
    print("2. Ela prepara um pedido do tipo GET.")
    print("3. Esse pedido viaja pela internet até o servidor.")
    print("4. O servidor entrega o pedido para o backend.")
    print("5. O backend entende que precisa da lista de produtos.")
    print("6. O backend consulta o banco de dados.")
    print("7. O banco devolve os produtos encontrados.")
    print("8. O backend organiza a resposta em JSON.")
    print("9. A resposta volta com o código 200.")
    print("10. A tela recebe tudo e mostra os produtos para o usuário.")
    print()
    print("Resumo da viagem:")
    print("clique → pedido → backend → banco → resposta → tela atualizada")
    print()
    print("Ideia de sobrevivência:")
    print("quando algo falha, você procura em qual parte dessa viagem o caminho quebrou.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def laboratorio_falhas_etapa_4():
    print()
    print("=" * 60)
    print("🧪 LABORATÓRIO DE FALHAS: QUANDO A RESPOSTA NÃO É 200")
    print("=" * 60)
    print("Nem toda viagem volta com sucesso.")
    print()
    print("Às vezes a tela manda o pedido,")
    print("o backend recebe,")
    print("mas a resposta volta com uma etiqueta diferente de 200.")
    print()
    print("Essa etiqueta ajuda você a descobrir onde procurar o problema.")
    print()
    print("Falhas comuns nessa ponte:")
    print()
    print("1. 400 — pedido incompleto")
    print("A tela mandou um pedido faltando alguma informação importante.")
    print()
    print("2. 401 — falta identificação")
    print("O sistema recebeu o pedido, mas não sabe quem está pedindo.")
    print()
    print("3. 404 — não encontrou")
    print("O pedido chegou, mas o backend não encontrou o que foi pedido.")
    print()
    print("4. 500 — erro dentro do servidor")
    print("O pedido chegou, mas algo quebrou dentro da casa:")
    print("backend, lógica ou banco.")
    print()
    print("Resumo de sobrevivência:")
    print("200 — deu certo.")
    print("400 — o pedido veio com problema.")
    print("401 — falta provar quem é.")
    print("404 — não encontrou o que foi pedido.")
    print("500 — quebrou algo dentro do servidor.")
    print()
    print("Fechamento:")
    print("Quando algo falha, você não precisa entrar em pânico.")
    print("Primeiro olhe a etiqueta da resposta.")
    print()
    print("Ela não resolve tudo sozinha,")
    print("mas mostra para qual lado você deve olhar:")
    print("pedido, login, endereço, backend ou banco.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def missao_producao_etapa_4():
    print()
    print("=" * 60)
    print("🏢 MISSÃO EM PRODUÇÃO: O PEDIDO NO MUNDO REAL")
    print("=" * 60)
    print("Agora a ponte sai do treinamento e entra em produção.")
    print()
    print("Imagine uma tela interna da CampOne chamada:")
    print('"Produtos disponíveis"')
    print()
    print("Essa tela precisa fazer duas coisas comuns em sistemas reais:")
    print()
    print("1. Mostrar os produtos que já existem.")
    print("2. Enviar um produto novo para ser cadastrado.")
    print()
    print("-" * 60)
    print("PRIMEIRO CAMINHO: VER OS PRODUTOS")
    print("-" * 60)
    print("Quando o usuário abre a tela de produtos,")
    print("a tela não está criando nada.")
    print()
    print("Ela só está perguntando ao backend:")
    print('"quais produtos existem?"')
    print()
    print("Esse tipo de pedido é chamado de GET.")
    print("A ideia é simples: buscar informação sem mexer em nada.")
    print()
    print("A viagem fica assim:")
    print()
    print("1. O usuário abre a tela de produtos.")
    print("2. A tela pede a lista ao backend.")
    print("3. O backend procura essa lista no banco de dados.")
    print("4. O banco devolve os produtos cadastrados.")
    print("5. O backend organiza a resposta.")
    print("6. A tela recebe a resposta e mostra os produtos.")
    print()
    print("-" * 60)
    print("SEGUNDO CAMINHO: CADASTRAR UM PRODUTO NOVO")
    print("-" * 60)
    print("Agora imagine que alguém da equipe cadastra um novo produto.")
    print()
    print("Nesse caso, a tela não está só olhando.")
    print("Ela está enviando uma informação nova para o backend.")
    print()
    print("Esse tipo de pedido é chamado de POST.")
    print("A ideia é: levar algo novo para o sistema guardar ou processar.")
    print()
    print("A viagem fica assim:")
    print()
    print("1. A pessoa preenche nome e preço do produto.")
    print("2. A tela envia essas informações ao backend.")
    print("3. O backend confere se o pedido faz sentido.")
    print("4. O backend pede para o banco guardar o novo produto.")
    print("5. O banco cria uma nova ficha.")
    print("6. O backend responde que deu certo.")
    print("7. A tela mostra a confirmação.")
    print()
    print("-" * 60)
    print("IDEIA DE SOBREVIVÊNCIA")
    print("-" * 60)
    print("Em produção, a ponte não é teoria distante.")
    print()
    print("Ela aparece toda vez que uma tela precisa buscar,")
    print("criar, atualizar ou apagar alguma informação.")
    print()
    print("Se você entende a viagem,")
    print("você entende onde procurar quando algo não aparece,")
    print("não salva ou volta com erro.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def prova_dominio_etapa_4():
    while True:
        print()
        print("=" * 60)
        print("✅ PROVA DE DOMÍNIO: A PONTE COMPLETA")
        print("=" * 60)
        print("Renato aparece na tela e olha diretamente para você.")
        print()
        print('"Agora vamos juntar a ponte inteira em uma cena só."')
        print()
        print("Um usuário abre a tela de produtos,")
        print("vê a lista,")
        print("cadastra um produto novo")
        print("e depois tenta abrir um produto que não existe.")
        print()
        print("PERGUNTA:")
        print("Qual leitura mostra melhor o que aconteceu nessa ponte?")
        print()
        print("1 - A tela faz tudo sozinha: cria, busca, apaga e decide os erros sem backend.")
        print("2 - Para ver a lista, a tela faz um pedido de busca. Para cadastrar, envia dados novos. Se um produto não existe, a resposta pode indicar que não encontrou.")
        print("3 - O banco aparece direto para o usuário e escolhe sozinho quais botões mostrar.")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "2":
            print()
            print("Renato confirma.")
            print('"Isso. Você juntou a ponte inteira:"')
            print('"buscar dados, enviar algo novo e ler uma resposta quando algo não é encontrado."')
            print()
            print("A ponte entre os mundos está dominada na teoria.")
            input("Pressione Enter para voltar...")
            break
        elif escolha == "1":
            print()
            print("Renato reancora com calma.")
            print('"Quase. A tela é a parte que o usuário vê e usa, mas ela não carrega o sistema inteiro sozinha."')
            print('"Ela precisa conversar com o backend para buscar, criar e receber respostas."')
            input("Pressione Enter para tentar novamente...")
        elif escolha == "3":
            print()
            print("Renato aponta para a separação das partes.")
            print('"Boa tentativa. O banco guarda dados, mas não conversa direto com o usuário."')
            print('"Normalmente, o backend faz a ponte entre a tela e o banco."')
            input("Pressione Enter para tentar novamente...")
        else:
            print()
            print("Escolha uma das opções: 1, 2 ou 3.")


def registro_etapa_4():
    print()
    print("=" * 60)
    print("📝 REGISTRAR EXPERIÊNCIA — A PONTE ENTRE OS MUNDOS")
    print("=" * 60)
    print("Renato aparece na tela e olha diretamente para você.")
    print()
    print('"Vamos registrar o que você atravessou nesta etapa."')
    print()
    print("Você reconheceu que:")
    print()
    print("- a tela não faz tudo sozinha;")
    print("- o frontend faz pedidos;")
    print("- o backend recebe, trabalha e responde;")
    print("- a API organiza os caminhos dessa conversa;")
    print("- GET busca informações sem mexer nos dados;")
    print("- POST envia algo novo para o sistema;")
    print("- PUT atualiza algo que já existe;")
    print("- DELETE remove algo que precisa sair;")
    print("- códigos como 200, 404 e 500 ajudam a entender o que aconteceu;")
    print("- o fluxo completo liga usuário, tela, pedido, backend, banco, resposta e tela atualizada.")
    print()
    print("Renato confirma:")
    print()
    print('"Isso ainda não é programação prática."')
    print('"É visão de sistema."')
    print()
    print('"Você agora entende a ponte antes de aprender a operar as ferramentas."')
    print()
    print("Experiência registrada apenas na narrativa.")
    print("Salvamento real será criado em uma fase futura.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def relatorio_final_etapa_4():
    print()
    print("=" * 60)
    print("📋 RELATÓRIO FINAL — A PONTE ENTRE OS MUNDOS")
    print("=" * 60)
    print("Renato aparece na tela e olha diretamente para você.")
    print()
    print('"Antes de seguir, revise a ponte inteira."')
    print()
    print("Relatório da missão: Construindo a Ponte dos Mundos")
    print()
    print("Você agora sabe que:")
    print()
    print("- frontend é a parte que o usuário vê e usa;")
    print("- backend é a parte que trabalha por trás;")
    print("- a comunicação entre os dois acontece por pedidos e respostas;")
    print("- API REST organiza os caminhos dessa conversa;")
    print("- GET é usado para buscar;")
    print("- POST é usado para enviar algo novo;")
    print("- PUT é usado para atualizar;")
    print("- DELETE é usado para apagar;")
    print("- códigos de resultado ajudam a diagnosticar o que aconteceu;")
    print("- o fluxo completo mostra a viagem do clique até a resposta na tela.")
    print()
    print("Conclusão:")
    print()
    print("Você começou a enxergar que todo app moderno depende dessa ponte.")
    print()
    print("Quando algo não aparece, não salva ou volta com erro,")
    print("você já sabe que existe um caminho para investigar:")
    print("tela, pedido, backend, banco ou resposta.")
    print()
    print("A etapa ainda não marca conclusão permanente nesta versão.")
    print("=" * 60)

    input("Pressione Enter para voltar...")


def entrar_etapa_4():
    while True:
        print()
        print("=" * 60)
        print("04. CONSTRUINDO A PONTE DOS MUNDOS")
        print("=" * 60)
        print("Tema real: Comunicação Frontend ↔ Backend")
        print("Tipo: Treinamento de Sobrevivência")
        print("Status: Estrutura inicial")
        print()
        print("CENTRO DE OPERAÇÕES")
        print("-" * 60)
        print("1 - Iniciar Missão")
        print("2 - Reconhecimento")
        print("3 - Campo de Treinamento")
        print("4 - Laboratório de Falhas")
        print("5 - Missão em Produção")
        print("6 - Prova de Domínio")
        print("7 - Registrar Experiência")
        print("8 - Relatório Final")
        print("0 - Retornar ao Nível 1")
        print("=" * 60)

        escolha = input("Escolha uma opção: ")

        if escolha == "1":
            cena_abertura_etapa_4()
        elif escolha == "2":
            reconhecimento_etapa_4()
        elif escolha == "3":
            campo_treinamento_etapa_4()
        elif escolha == "4":
            laboratorio_falhas_etapa_4()
        elif escolha == "5":
            missao_producao_etapa_4()
        elif escolha == "6":
            prova_dominio_etapa_4()
        elif escolha == "7":
            registro_etapa_4()
        elif escolha == "8":
            relatorio_final_etapa_4()
        elif escolha == "0":
            break
        else:
            print()
            print("Opção inválida.")
